### ISSUE TITLE
Fatal error, I need help

### ISSUE THREAD

**Issue by FRanc0o0297** [themrdemonized/STALKER-Anomaly-modded-exes#12]
Hello, I had this error when I put the files in the folder where the game was, how could I solve it?

There is the error
![Captura de pantalla (1)](https://user-images.githubusercontent.com/117410915/199849608-2b1529e7-1185-4e8d-b85c-f481716a7ef9.png)

**Comment by themrdemonized** [comment]
Some mod have incorrect xml file according to parser.

- Find dxml_core.script, then in the file find "local xml_string_debug_enabled = false" string and change it to true.
- Launch the game, wait for crash
- Open crash log in stalker anomaly/appdata/logs/xray_...log file
- in the log there should be list of xml files which are loaded and parsed, for example "dialogs.xml loaded" and so on. Find the latest one thats loaded and before the crash message appears in the log
- Send me full log with that file here or in discord, demonized#1084

**Comment by infamousjellyfish** [comment]
Having same error when installed the latest modded exes, can you help me ?

**Comment by themrdemonized** [comment]
The error you posted has nothing to do with the one in the issue. tell the author of the mod you are using about it
