### ISSUE TITLE
Уровень зума прицела не может быть отрегулирован;Необходимо обновить компонент установки: [Регулируемый дальномерный прицел] Уровень увеличения прицела невозможно настроить для огнестрельного оружия с функцией Adjustable sightg.

### ISSUE THREAD

**Issue by zanghuashenwu** [themrdemonized/STALKER-Anomaly-modded-exes#17]
Автор, пожалуйста, помогите мне.
Я скачал с форума файлы обновления для 1.5.1 и 1.5.2.
После установки 1.5.2 EXES (DLTX) на [https://github.com/themrdemonized/STALKER-Anomaly-modded-exes], снайперские винтовки с собственными прицелами (например, VVS, LA96A, SV98) необходимо обновить с помощью компонента установки: [Adjustable range-finder sight] Оружие, получившее функцию Adjustable sightg, не может настроить уровень увеличения прицела.
Что мне делать?
Я пробовал удалять шейдеры и восстанавливать настройки, но это все равно не работает
/(ㄒoㄒ)/

EN:
Author, please help me.
I downloaded the update files for 1.5.1 and 1.5.2 from the forum.
After installing 1.5.2 EXES (DLTX) on [https://github.com/themrdemonized/STALKER-Anomaly-modded-exes], except for the "Bobcat SVD" and some sniper rifles with built-in zoom sights, other sniper rifles with their own scopes (e.g. VVS, LA96A, SV98) need to upgrade the installation component: [Adjustable range-finder sight] Guns that get the Adjustable sightg feature cannot adjust the scaling level of the sights.
What should I do?
I've tried deleting the shader and restoring the settings, but it still doesn't work

**Comment by themrdemonized** [comment]
if you cant adjust the zoom level on some scopes, then thats how it is setted up in weapon config

**Comment by zanghuashenwu** [comment]
> if you cant adjust the zoom level on some scopes, then thats how it is setted up in weapon config
1.5.2 pure version of the game no problem, but after installing only a DLTX [exes], you need to upgrade the sniper rifle of the second level scalable scope, the upgrade will not be able to get the zoom function. Is this file you are talking about within the DLTX file specifically which one? I'm sorry for the machine flip that doesn't work well in English and Russian.

**Comment by zanghuashenwu** [comment]
> if you cant adjust the zoom level on some scopes, then thats how it is setted up in weapon config

1.5.2 pure version of the game no problem, but after installing only a DLTX [exes], you need to upgrade the sniper rifle of the second level scalable scope, the upgrade will not be able to get the zoom function. Is this file you are talking about within the DLTX file specifically which one? I'm sorry for the machine flip that doesn't work well in English and Russian.

**Comment by themrdemonized** [comment]
Now i got it, its about upgrades. I'll check it out later

**Comment by zanghuashenwu** [comment]
> 现在我明白了，它是关于升级的。我稍后会查看



> Now i got it, its about upgrades. I'll check it out later

I'm using your dltx-v7 from moddb website. maybe he's 1.5.1 and it's currently upgradable and scalable. But maybe that would be a problem? Although I seem to have installed only one weapon mod that requires DLTX.

**Comment by zanghuashenwu** [comment]
Is there a DLTX archive for older versions of 1.5.2? , I can't play the game now and urgently need an old version of 1.5.2, please.

**Comment by themrdemonized** [comment]
try the latest version please

**Comment by zanghuashenwu** [comment]
> try the latest version please
You are my hero, he fixed it! Thanks for your help!
