### ISSUE TITLE
scope_factor settings applied to disabled shader scope AGAIN

### ISSUE THREAD

**Issue by donizettilorenzo** [themrdemonized/STALKER-Anomaly-modded-exes#18]
In some later changelogs

"Fixed the bug where scope_factor settings were applied to disabled shader scopes or scopes without defined radius for shader effect"

But with the lastest version the bug is here again. I disable the support for SSS (i'm using it) within ACM to disable the shader but scope_factor doesn't "reset" to 1.

**Comment by themrdemonized** [comment]
it doesnt matter what the console variable is if shader scopes are disabled

**Comment by donizettilorenzo** [comment]
But the problem is that the script is still running.

**Comment by donizettilorenzo** [comment]
See this sequence with r__fakescope set to ZERO (scopes disabled in ACM\SSS)

https://i.postimg.cc/7ZBX7cHc/0.jpg
https://i.postimg.cc/gjD3pXr5/1.jpg
https://i.postimg.cc/1tDpWYSy/2.jpg
https://i.postimg.cc/yNMmyCwf/3.jpg


As you can see the script is running nonetheless.....

**Comment by themrdemonized** [comment]
to disable shader scopes use sds_enable 0

**Comment by donizettilorenzo** [comment]
Maybe it's a good thing to add 2 entries to ACM menu options, one for compatibility with SSS and one to enable/disable the main script!

**Comment by themrdemonized** [comment]
you can forward the issue to SSS creator
