### ISSUE TITLE
Request to modify artefact_count to use values from system.ltx instead of being hard coded 

### ISSUE THREAD

**Issue by zekuzodia** [themrdemonized/STALKER-Anomaly-modded-exes#21]
![image](https://user-images.githubusercontent.com/70095346/228819103-5ceffb81-c070-48cf-9d67-2bcfe31c5b72.png)

**Comment by themrdemonized** [comment]
alright, you have to ensure that the ui will have the possibility to display more than 5 artefacts as well

**Comment by themrdemonized** [comment]
Added in the latest version, no upper engine limit for max artefacts, the limit is only by the outfit
