### ISSUE TITLE
How to use SetHitPower(float) function listed in lua_help_ex?

### ISSUE THREAD

**Issue by Orelarsen** [themrdemonized/STALKER-Anomaly-modded-exes#24]
When I use it in my script it crashes with message :
LUA error: ...anomaly 1.5.2\gamedata\scripts\charge_gauss_rifle.script:34: attempt to call method 'SetHitPower' (a nil value)

**Comment by Orelarsen** [comment]
Edit: this problem happens with all of these functions

**Comment by themrdemonized** [comment]
try obj:cast_Weapon():SetHitPower(4.2)

**Comment by Orelarsen** [comment]
Thanks a million, mister demonized.
