### ISSUE TITLE
Is this error mod-related or not? (address 0x0000000140210A49)

### ISSUE THREAD

**Issue by trendoman** [themrdemonized/STALKER-Anomaly-modded-exes#25]
My new modded game is not very stable, I am disabling mods although issues are sporadic. However this one happened out of the blue.. So can you tell if this is mod-related or not? I am attaching minidump and will try to see if it persists without mods.
Thx!

```
[error][      87] : The parameter is incorrect.

at address 0x0000000140210A49
```

[xray_anton.zip](https://github.com/themrdemonized/STALKER-Anomaly-modded-exes/files/11585527/xray_anton.zip)

**Comment by themrdemonized** [comment]
oops, i missed this issue after today's update. Can you please redownload new version of exes and replicate the crash once again with minidump attached?

**Comment by trendoman** [comment]
Ofc I will always try to replicate it with the latest exes, although crash might take a while to present itself. I will reopen the issue. Thx!
