### ISSUE TITLE
CTD without notice

### ISSUE THREAD

**Issue by trendoman** [themrdemonized/STALKER-Anomaly-modded-exes#26]
Hi, in #25 I mentioned testing game with mods, so far the only problematic one is the FDDA. I know you are not responsible for 3rd party code (and FDDA has not been updated in a while) and there may be some hidden conflicts. However if you are interested, here is what I had with the latest EXEs:

[xray_anton.zip](https://github.com/themrdemonized/STALKER-Anomaly-modded-exes/files/11594179/xray_anton.zip)

(mods in MO2 have no conflicts and do not require new game, screenshot attached)

1. I moved to another level (RedForest->Jupiter) 
2. had a fight and popped a medkit, animation did not happen, input froze but I still could move, but could not equip anything (this is a popular issue i guess), then
3. I loaded an autosave from the level change and this produced a CTD, logs attached. No popup, no other notice, just desktop.

Ofc, removing FDDA completely (not just disable) helps, but I guess you might wonder why engine does not pop up alert upon CTD.

Hope it helps.
P.S. This issue is new, coz the error is different (at address `0x00000001401C1F6F`)

**Comment by themrdemonized** [comment]
I watched the minidump and i couldnt figure out whats wrong, its just garbage. The mods are certainly the proble but i cant tell which ones
