### ISSUE TITLE
New feature: adjustable Leaning angle

### ISSUE THREAD

**Issue by Grokitach** [themrdemonized/STALKER-Anomaly-modded-exes#28]
Currently leaning angle is hard coded to Pi / 4 which is a shame.

Adjustable leaning angle by console command would allow different things, such as simple comfort changes for the player, but also new gameplay elements, such as increasing the leaning angle for easy to handle / lightweight guns vs short angle for big guns or when using a scope. That is since a high leaning angle makes the gun easier to use from a cover since more of your body will be covered with a high angle vs a low angle.

Here are some leads to make the change:

src/xrGame/Actor_Movement.cpp:371,372  > change PI_DIV_4 to console command value between 1 (no angle) and 0.5 (horizontal, thus must look dumb though).
```
#define ACTOR_LLOOKOUT_ANGLE	PI_DIV_4
#define ACTOR_RLOOKOUT_ANGLE	PI_DIV_4
```

or

src/xrGame/Actor_Movement.cpp:427 > add a console command value as a multiplier.
```
tgt_roll = (mstate_rl & mcLLookout) ? -ACTOR_LLOOKOUT_ANGLE : ACTOR_RLOOKOUT_ANGLE;
```

**Comment by themrdemonized** [comment]
![изображение](https://github.com/themrdemonized/STALKER-Anomaly-modded-exes/assets/46323442/6b8b29c2-c346-4fb3-9b61-01200654cd11)
my proposal - new lua functions to adjust lean modifier. by default modifier is 1.

**Comment by Grokitach** [comment]
Seems good :) ! Is there a range of values for the modifier ?

**Comment by themrdemonized** [comment]
added since 2023.06.30
