### ISSUE TITLE
Frametime issues, stuttering

### ISSUE THREAD

**Issue by aorushome** [themrdemonized/STALKER-Anomaly-modded-exes#3]
The 1.5.2 executables appear to increase stutter and spikes. Please reffer to this post at moddb.
https://www.moddb.com/mods/stalker-anomaly/forum/thread/anomaly-151-vs-152-frametimes/#1118194

Tested with the same game, same modifications, same savefile.
Can this be caused by something you changed or did different in the assembling process, compared to the 1.5.1 executables?

**Comment by GabrielRanghetti** [comment]
That too is happening with me. I limited my framerates to 120 fps and it's constantly something like 115 ~ 118 fps, if I limit to 100 fps it still shows something like 95 ~ 98 fps.

**Comment by HeicoDev** [comment]
I got the same issue

**Comment by aorushome** [comment]
Frametime issue was solved by editing / removing "Arszi's Burer Overhaul".
Dont know why I didnt find this earlier, the whole console was basically spammed from his actor_on_update calls.
Maybe it helps someone else, since many ppl seem to use it with 1.5.2.

! [LUA] CSciptEntity : cannot access class member Alive!
! [LUA]  0 : [C  ] alive
! [LUA]  1 : [Lua] ... - the zone 208 test\gamedata\scripts\arszi_burer.script(87) : manage_burer_blinding

So the stutter didnt had anything to do with the files here.
Sadly, it still doesnt change the fact, that the author is too unresponsive and uncooperative.
