### ISSUE TITLE
Patching my own branch

### ISSUE THREAD

**Issue by WarezzK** [themrdemonized/STALKER-Anomaly-modded-exes#30]
Hello, What is this mean? This is happening when i want apply allinone patch to my clone engine repo.
![image](https://github.com/themrdemonized/STALKER-Anomaly-modded-exes/assets/9317317/8c3b6b2a-435b-4686-87f7-096e7678a956)

This is in console
![image](https://github.com/themrdemonized/STALKER-Anomaly-modded-exes/assets/9317317/9b50df41-6749-47ed-89dd-4e32e5183301)

**Comment by themrdemonized** [comment]
make a brand new branch from "master" branch, and apply all-in-one.diff patch onto it. i just tested, works fine. This is what should you see
![изображение](https://github.com/themrdemonized/STALKER-Anomaly-modded-exes/assets/46323442/0bdcb7b1-2a4e-4a14-a1f0-c1a98addff02)

**Comment by WarezzK** [comment]
![image](https://github.com/themrdemonized/STALKER-Anomaly-modded-exes/assets/9317317/e1071e71-70dc-4bfe-a022-e2401766a8b5)
 It's very weird. I create branch, switch to new branch then again. Even the path to repository is short and without characters, blank spaces etc.

**Comment by WarezzK** [comment]
Weird. I clone clean repo of anomaly xray from your link, i create new branch, my path to repository is short, no whitespaces, characters etc. Even GIT is updatet to latest version and still. That's weird.  
![image](https://github.com/themrdemonized/STALKER-Anomaly-modded-exes/assets/9317317/501057cd-c799-4e2e-9235-d01bfe393fdc)
