### ISSUE TITLE
Game Won't even launch

### ISSUE THREAD

**Issue by Sidtheplayer** [themrdemonized/STALKER-Anomaly-modded-exes#32]
can't even start the game whether it maybe from mod organizer or default launcher
when i installed your latest modded exes my game stopped launching altogether i dont even get the stalker anomaly photo in middle of my screen or see it in task manager

**Comment by themrdemonized** [comment]
https://github.com/themrdemonized/STALKER-Anomaly-modded-exes#read-the-instructions-please

**Comment by Sidtheplayer** [comment]
> https://github.com/themrdemonized/STALKER-Anomaly-modded-exes#read-the-instructions-please

i did as requested in instructions but the game wont launch
i reinstalled your modded exes 
it asked if i want to overwrite files and i clicked yes

**Comment by Sidtheplayer** [comment]
i now removed reshade and it still wont work

**Comment by themrdemonized** [comment]
you need to update the c++ redist, there is a link

**Comment by Sidtheplayer** [comment]
still no luck whatsoever

**Comment by Sidtheplayer** [comment]
please reply i cant start game with my mods now   
i installed all C++ redist but it wont start

**Comment by themrdemonized** [comment]
you can find previous versions there https://github.com/themrdemonized/STALKER-Anomaly-modded-exes/commits/main i can't help further, sorry

**Comment by Sidtheplayer** [comment]
i think your newer versions are bugged as once i switched to older ones the game is working fine

**Comment by Sidtheplayer** [comment]
maybe they are only for win 11 users

**Comment by themrdemonized** [comment]
I tested it in VM on windows 7 and of course my install on Win 10, works fine

**Comment by themrdemonized** [comment]
Check version 2023.08.08
AVX version will probably crash, normal versions should work fine
