### ISSUE TITLE
Начиная с версии 2023.07.24, которые уже создаются с помощью Visual Studio 2022, игра перестала запускаться

### ISSUE THREAD

**Issue by GIGAVETER** [themrdemonized/STALKER-Anomaly-modded-exes#33]
Начиная с версии 2023.07.24, которые уже создаются с помощью Visual Studio 2022, игра перестала запускаться.
Последние Visual C++ Redistributables устанавливаются из набора, предложенного в описании, на Windows 7 64bit.

Содержание двух записей в журнале событий:

Имя сбойного приложения: AnomalyDX11.exe, версия: 1.0.5.5, отметка времени: 0x64cea959
Имя сбойного модуля: AnomalyDX11.exe, версия: 1.0.5.5, отметка времени 0x64cea959
Код исключения: 0xc000001d
Смещение ошибки: 0x00000000000b6e6b
Идентификатор сбойного процесса: 0x285c
Время запуска сбойного приложения: 0x01d9c7e561451e04
Путь сбойного приложения: D:\Games\Anomaly-1.5.2\bin\AnomalyDX11.exe
Путь сбойного модуля: D:\Games\Anomaly-1.5.2\bin\AnomalyDX11.exe
Код отчета: 9f749484-33d8-11ee-8ffc-309c238706bc

- System 

  - Provider 

   [ Name]  Application Error 
 
  + EventID 1000 

   [ Qualifiers]  0 
 
   Level 2 
 
   Task 100 
 
   Keywords 0x80000000000000 
 
  - TimeCreated 

   [ SystemTime]  2023-08-05T21:39:58.000000000Z 
 
   EventRecordID 32990 
 
   Channel Application 
 
   Computer Odin-PC 
 
   Security 
 
- EventData 

   AnomalyDX11.exe 
   1.0.5.5 
   64cea959 
   AnomalyDX11.exe 
   1.0.5.5 
   64cea959 
   c000001d 
   00000000000b6e6b 
   285c 
   01d9c7e561451e04 
   D:\Games\Anomaly-1.5.2\bin\AnomalyDX11.exe 
   D:\Games\Anomaly-1.5.2\bin\AnomalyDX11.exe 
   9f749484-33d8-11ee-8ffc-309c238706bc 
-----------------------------------------------------------
Нет доступа к файлу  по одной из следующих причин: либо возникли проблемы с сетевым подключением, диском с файлом или хранилищем с драйверами, установленными на этом компьютере, либо этот диск отсутствует. Программа X-Ray Monolith Engine будет закрыта из-за этой ошибки. 
 
Программа: X-Ray Monolith Engine 
Файл:  
 
Код ошибки приведен в разделе "Дополнительные данные". 
Действие пользователя 
1. Снова откройте файл. Проблема может быть временной и исправится сама собой при повторном запуске программы. 
2. Если к файлу все равно нет доступа и при этом: 
	- он расположен на сетевом диске, сетевой администратор должен проверить, что сеть работает нормально и что к серверу есть доступ. 
	- он находится на съемном диске, например на дискете или компакт-диске, убедитесь, что диск полностью вставлен в компьютер. 
3. Проверьте и восстановите файловую систему с помощью команды CHKDSK. Чтобы запустить команду CHKDSK, щелкните "Пуск", "Выполнить", введите "CMD" и нажмите "ОК". В командной строке введите команду "CHKDSK /F" и нажмите клавишу "ВВОД". 
4. Если не удалось устранить проблему, восстановите файл из архивной копии. 
5. Проверьте, можно ли открыть другие файлы на этом же диске. Если нет, то возможно, что диск поврежден. Если это жесткий диск, обратитесь за помощью к системному администратору или изготовителю оборудования. 
Дополнительные данные 
Значение ошибки: 00000000 
Тип диска: 0

- System 

  - Provider 

   [ Name]  Application Error 
 
  - EventID 1005 

   [ Qualifiers]  49152 
 
   Level 2 
 
   Task 100 
 
   Keywords 0x80000000000000 
 
  - TimeCreated 

   [ SystemTime]  2023-08-05T21:39:58.000000000Z 
 
   EventRecordID 32991 
 
   Channel Application 
 
   Computer Odin-PC 
 
   Security 
 

- EventData 

    
   X-Ray Monolith Engine 
   00000000 
   0

**Comment by themrdemonized** [comment]
Есть ли в appdata/logs файлы mdmp?

**Comment by GIGAVETER** [comment]
Нет, вообще никаких файлов с данными об ошибке не появляется.

**Comment by themrdemonized** [comment]
Абсолютно все dx версии крашатся?

**Comment by GIGAVETER** [comment]
AnomalyDX9.exe запустился (из последнего набора exe).

**Comment by themrdemonized** [comment]
попробуй этот набор: https://drive.google.com/file/d/1cHEN2nsEKXxnobD0g9jT_cUv7VLdyhVF/view?usp=sharing

**Comment by themrdemonized** [comment]
И еще скажи какой проц и видюха у тебя

**Comment by GIGAVETER** [comment]
Спасибо за отзывчивость, к сожалению ни один exe не запустился.

CPU - Intel Pentium G4560

GPU - NVIDIA GeForce GT 640

**Comment by themrdemonized** [comment]
попробуй тогда эти: https://drive.google.com/file/d/1cHEN2nsEKXxnobD0g9jT_cUv7VLdyhVF/view?usp=sharing
AVX скорее всего не запустятся, обычные должны работать

**Comment by GIGAVETER** [comment]
Все запустились на чистой Anomaly 1.5.2, можно начать новую игру, дальше не тестировал; также на сборке с модами заработал AnomalyDX11.exe (другие  пробовал только до главного меню).

Прекрасная работа!

Можно ли надеяться, что дальнейшие общедоступные сборки будут сделаны с по такому же способу, или это единичный эксклюзив для отсталого семёрочника?

Ещё раз огромное спасибо за отзывчивость!

**Comment by themrdemonized** [comment]
Проверь версию 2023.08.08

**Comment by GIGAVETER** [comment]
На этот раз напишу правильнее - в сборке 2023.08.08 все не-AVX версии запустились на сборке с модами, загружалось сохранение (AVX не поддерживается моим ЦП).

Закрываю тему как решённую.

**Comment by themrdemonized** [comment]
Если сможешь, попробуй вот эту версию еще, они скомпилированы другим способом: https://drive.google.com/file/d/1cHEN2nsEKXxnobD0g9jT_cUv7VLdyhVF/view?usp=sharing

**Comment by GIGAVETER** [comment]
> Если сможешь, попробуй вот эту версию еще, они скомпилированы другим способом: https://drive.google.com/file/d/1cHEN2nsEKXxnobD0g9jT_cUv7VLdyhVF/view?usp=sharing

Доброго дня!
Испробовал - все не-AVX версии успешно запустили игру и загрузили сохранение.
