### ISSUE TITLE
2023/08/05 and 2023/08/06 exes breaks several HUD animations

### ISSUE THREAD

**Issue by York2016** [themrdemonized/STALKER-Anomaly-modded-exes#34]
Starting from the 2023/08/05 exes some HUD animations have become broken.
 Noticeably, the Mask Wipe and Headlamp animations do not play.
In addition, i personally also have issues with Dynamic Dialog UI not working properly (although it seems that i am the only one who encountered it so it may just be a fluke).
 There may be more issues but that is what people have noticed with a short time playing with those builds.

Reverting to 2023/07/28 or the SSS 17.0 exes fixes these issues.

**Comment by idcurse** [comment]
Hi.The same problem with animations FDDA .They became crooked .

**Comment by ogkush920** [comment]
can you link me with 2023/07/28 modded exes? im having the same issues as u, broken animations since updating this

**Comment by idcurse** [comment]
https://disk.yandex.ru/d/2Fqa2pM0IGkAbA  2023.07.28

**Comment by themrdemonized** [comment]
> can you link me with 2023/07/28 modded exes? im having the same issues as u, broken animations since updating this

Commit history has all previous versions

**Comment by themrdemonized** [comment]
fixed in 2023.08.07
