### ISSUE TITLE
reShade

### ISSUE THREAD

**Issue by billlcarr** [themrdemonized/STALKER-Anomaly-modded-exes#36]
reShade doesn't work with the latest binaries. The interface opens and appears to be functioning normally, but it has no visible effect.

**Comment by themrdemonized** [comment]
You need full addon support version of reshade installed, preferably 5.7.0

**Comment by billlcarr** [comment]
I've done a clean install of the full addon support version of 5.7.0 (the installer name is "ReShade_Setup_5.7.0_Addon.exe"), and it still doesn't work. In the reshade interface, under the "Add-ons" tab, "Stalker Anomaly" is present and is checked. Is there any other setting I need to change or procedure I need to do?

**Comment by themrdemonized** [comment]
do you have any actual shaders installed?

**Comment by billlcarr** [comment]
Yes. I have shaders installed, as well as a preset, that all works when I switch back to the older EXEs. As soon as I switch to the newest EXEs, it stops having a visible effect.

**Comment by themrdemonized** [comment]
What directx do you use?

**Comment by billlcarr** [comment]
DirectX 11 AVX

**Comment by themrdemonized** [comment]
can you drop the log, there should be a reshade string

**Comment by billlcarr** [comment]
Sure thing-

https://pastebin.com/uT7Dhc1M

**Comment by themrdemonized** [comment]
the compatibility addon is loaded, so it should work fine. idk whats wrong with it

**Comment by billlcarr** [comment]
Yeah, the add-on shows up in the reShade "add-ons" tab as well. It's really bizarre. reShade is definitely installed properly, because it works when I replace these binaries with the ones from SSS 16.

**Comment by billlcarr** [comment]
Don't know if this could be useful, but here's the dxgi log from reShade

https://pastebin.com/mswwPdiW

**Comment by themrdemonized** [comment]
i think reshade uses Reshade.log, what you posted tells it is really old 5.0.0. verison

**Comment by billlcarr** [comment]
Sorry, you're right, that must have been left over from a previous install. Here's the reshade log

https://pastebin.com/LJM42kZt

**Comment by KonstAl54** [comment]
same issue. install new sss and exe`s  and it`s didnt work.  back up old exe`s  reshade works

**Comment by themrdemonized** [comment]
try this pack, see if it still persists: https://drive.google.com/file/d/1cHEN2nsEKXxnobD0g9jT_cUv7VLdyhVF/view?usp=sharing

**Comment by billlcarr** [comment]
Same thing. The reShade interface functions normally, Stalker Anomaly is listed and checked in the Add-Ons tab, but none of the shaders have any visible effect.

**Comment by themrdemonized** [comment]
idk it definitely should have an effect, i cant reproduce the issue, it just works. try some extreme preset in actual game. the ui wont be affected, including whole main menu screen

**Comment by billlcarr** [comment]
Ok, I'm an idiot... I was testing it on the main menu... It's working. Thanks. Sorry to have bothered you with this nonsense.

**Comment by KonstAl54** [comment]
> try this pack, see if it still persists: https://drive.google.com/file/d/1cHEN2nsEKXxnobD0g9jT_cUv7VLdyhVF/view?usp=sharing

no, reShade  didn`t work with this exes also
