### ISSUE TITLE
Problem with Quick Melee add-on

### ISSUE THREAD

**Issue by billlcarr** [themrdemonized/STALKER-Anomaly-modded-exes#38]
After updating to the latest binaries, quick melee no longer breaks boxes. The animation works normally, and it does damage to NPCs, but it does nothing to the breakable wooden crates.  Quick melee starts working normally again if I switch to the binaries that were included in SSS 16.

**Comment by themrdemonized** [comment]
what quick melee mod you use

**Comment by billlcarr** [comment]
Quick Melee Reworked. The one by Feelfried.

**Comment by themrdemonized** [comment]
works for me, no issues

**Comment by billlcarr** [comment]
That's strange. I've been using Quick Melee for a long time with no problems, and it currently works fine with the SSS 16 binaries, but switching to either the recent binaries here, or the ones included with SSS 17, and quick melee stops breaking wooden crates.

**Comment by billlcarr** [comment]
When you say it works with no issues, did you try to break a wooden crate? Because the animation does work like normal, it just doesn't break wooden crates like it should.

**Comment by themrdemonized** [comment]
yes i tested all crates, wooden, metal, enemies, walls

**Comment by billlcarr** [comment]
Really strange. I'm not the only one experiencing it. There's at least 2 other users who mentioned it in the SSS comments. No idea what it could possibly be other than the exe when it works with one, but not the other. If it was a mod conflict the exe would be irrelevant, and if it wasn't installed properly it wouldn't work with either. I'm at a loss.

**Comment by viking896** [comment]
please fix your exe since the last updates some things don't work properly like quick meele i'm not the only one who noticed the error ;)

**Comment by nekomaster** [comment]
I too have noticed this issue and have resorted to using the Modified EXE's from my old modpack backup.

Quick melee rework just doesnt work properly with recent Modified EXE versions as mentioned previously, where I cannot smash/break destructable objects like crates and cardboard boxes.

This happens even if all I have loaded is just MCM and Quick Melee Reworked

**Comment by themrdemonized** [comment]
i found the problem, will be fixed in the next update

**Comment by nekomaster** [comment]
> i found the problem, will be fixed in the next update

OH THANK GOD, It really sucked not being able to just smash stuff open with a bare fist or a rifle to save on ammo (and maybe a little less noisy than say, shooting a crate open)

**Comment by billlcarr** [comment]
Awesome! Thanks so much!

**Comment by themrdemonized** [comment]
try the latest version

**Comment by billlcarr** [comment]
You rock, dude! It works. Thanks!
