### ISSUE TITLE
Starting a new game on fresh install, crashes....

### ISSUE THREAD

**Issue by ogkush920** [themrdemonized/STALKER-Anomaly-modded-exes#40]
title says it all. Ive done a fresh install several times, the game works before adding your modded exes, when adding your modded exes it crashes with no error report found in logs. every single time. so I downloaded your 7/28 modded exes and now its working perfectly fine again.

**Comment by ogkush920** [comment]
and just to note, also when starting a new game. I deleted my old saves because of some new mods I added. spent all day thinking it was changes in my mods since i have 100+ installed n tweaked to be compatible, but then I disabled them all and several fresh installs later came realized it was the updated modded exes

**Comment by themrdemonized** [comment]
What dx you tried, is it avx or not
