### ISSUE TITLE
Sound

### ISSUE THREAD

**Issue by idcurse** [themrdemonized/STALKER-Anomaly-modded-exes#41]
Hi . JSRS and SoundscapeOverhaul are installed .when exiting the dungeons of the agro - industry , the sound of the dungeon remains for some time , the first throw of the grenade is without sound . also in the dark valley, near the seller, the radio plays as if it was moved to another room.directly near the seller-silence .I checked it several times . returned on 07.28.2023 - everything is fine .

**Comment by themrdemonized** [comment]
Hi,  nothing changed to the sound system, check your mods

**Comment by idcurse** [comment]
Привет .Посмотрел,нах через перевод пишу) с гранатами и эмбиентом что то было,сам не знаю что,но всё работает.а вот с торговцем бандосов  в тёмной долине ,явно что то не так. как и писал ,звук радио ушёл в другое место . 28.07.2023 всё норм. последнее обновление-возле торговца вообще ничего не слышно,внизу тоже ,а вот в соседней комнате орёт .
