### ISSUE TITLE
feature request: disable weapon swap with a mouse wheel

### ISSUE THREAD

**Issue by BlackburnUTG** [themrdemonized/STALKER-Anomaly-modded-exes#44]
IDK if this is the right place to ask. When you unbind previous/next weapon key in options - you can still swap weapons with mouse wheel.
This thing drives me crazy: you can't unbind it. Can we have a mod or something to disable this annoying feature?

**Comment by themrdemonized** [comment]
i can comeup with something

**Comment by themrdemonized** [comment]
Added in 2023.09.30

**Comment by BlackburnUTG** [comment]
you are THE wizard, man! Thank you so much!
