### ISSUE TITLE
Can NPCs be made  react to priority danger

### ISSUE THREAD

**Issue by Bamah7** [themrdemonized/STALKER-Anomaly-modded-exes#47]
Much like this from CoC last engine. 
"Made adjustments to xr_danger. Stalkers should now properly react to new danger and there is even a priority to when new danger should override the danger the stalker is already reacting to, which should make it less likely they will ignore 'attacked' danger for something like 'bullet ricochet' which has a lower reaction timer."
 or
"danger | Previously it has always been the case that new danger would overwrite existing danger, even if danger was processed to be false because it was hardcoded which danger was selected from memory. For example, if you killed a npc it then caused danger_object.attacked then danger_object.corpse dangers, but if bullet hit ground and created ricochet danger then the remaining npcs would be concerned about ricochet danger, which is where they just crouch and look at ricochet spot. If scheme evaluated that npc shouldn't react to ricochet danger, then npc wouldn't react at all. In engine has been added the ability to remove danger objects from npc. Now in xr_danger if danger is evaluated to be false, then danger is removed with npc:remove_danger(danger_object), which allows the npc to find and select a new danger object from memory. Hopefully, now they should react to priority danger."

**Comment by themrdemonized** [comment]
xr_danger is a script and can be edited by anyone, i think there are some mods for anomaly that edits that, its not an engine issue

**Comment by Bamah7** [comment]
Thank you. I have edited the script extensively. The priorities do not seem
to hold when engaged in combat. I've had great results changing
cambat_ignore to help different issues
Biggest issue I see is if you shoot at an NPC, and miss he never reacts to
the sound of the weapon firing, or if during combat he switches to looting
scheme he is oblivious to being shot/hit  and continues looting. I've
played with the xr_danger.ltx file a lot. Any insight.
Thank you.

**Comment by Bamah7** [comment]
Thanks for the time, sincerely. That does not work correctly. I'll keep
mine and continue on.
I almost have a balance between danger, combat ignore and camper. If I
shoot at an NPC, the entire squad will hammer my position and remain doing
so till my extended timer runs out. They, will then move on my position,
unless the looting scheme kicks in and one will loot and forget actor was a
"danger". Other than that perfect. I won't bother you anymore.
