### ISSUE TITLE
feature request: can mouse scroll wheel be not inverted?

### ISSUE THREAD

**Issue by BlackburnUTG** [themrdemonized/STALKER-Anomaly-modded-exes#50]
Right now when you use pda map, or zoom with binoculars or scopes - you need to scroll mouse wheel in oposite direction.
Scroll down for zoom up
Scroll up - for zoom down
can it be changed to normal?

**Comment by themrdemonized** [comment]
type in console mouse_wheel_invert_zoom 0

**Comment by BlackburnUTG** [comment]
> type in console mouse_wheel_invert_zoom 0
error - there is no such command
plus when I tring to search it with key "word" - can find it too
![image](https://github.com/themrdemonized/STALKER-Anomaly-modded-exes/assets/19798113/e88c12eb-6d05-41ca-a6a5-2357e1c8b649)

**Comment by BlackburnUTG** [comment]
ah, lol. I didnt see that you made a new verion
