### ISSUE TITLE
FDDA detects wrong version

### ISSUE THREAD

**Issue by Haruuky** [themrdemonized/STALKER-Anomaly-modded-exes#51]
![STALKER FDDA Issue](https://github.com/themrdemonized/STALKER-Anomaly-modded-exes/assets/136552022/b858e1e8-88ac-482f-af68-90df54bcad16)

For some reason when I use the modified EXES the FDDA addon detects it as if I am on 1.5.1 when in fact I am on 1.5.2. All my addons are updated to version 1.5.2.

Anyway, if I press the "ok I don't care" button the game works without any problems, except for this message appearing every time I load a game, which is kind of annoying.

**Comment by themrdemonized** [comment]
Its a problem with your installation. reinstall rhe game correctly (1.5.1 then 1.5.2 update then modded exes)
