### ISSUE TITLE
Gray (read description I am terrible with Titles) 

### ISSUE THREAD

**Issue by Dyspor** [themrdemonized/STALKER-Anomaly-modded-exes#52]
Well when I want to play Anomaly it works but its White (you can see edges of objects but its a whity-gray turn the cam and it becomes black or its flickering. 
I played with mods, then tried every mod (maye the issue comes from there.)
Turing off all mods so the game runs vanilla only with the Modded EXEs the game remains with the same issue.

I will place here the lastes Log i hope it would help you and me solving it. I use the lastes version of you: 2023.10.26
[xray_devid.log](https://github.com/themrdemonized/STALKER-Anomaly-modded-exes/files/13241232/xray_devid.log)

**Comment by themrdemonized** [comment]
did you follow the install instructions?
