### ISSUE TITLE
you can't sprint when you are leaning with Q/E

### ISSUE THREAD

**Issue by BlackburnUTG** [themrdemonized/STALKER-Anomaly-modded-exes#54]
can this strange behaviour be fixed? Sprint should cancel leaning

**Comment by themrdemonized** [comment]
do you use toggle lean?

**Comment by themrdemonized** [comment]
anyways, google mod first so i wont need to
https://www.moddb.com/mods/stalker-anomaly/addons/sprint-cancel-aim-and-lean-toggle
