### ISSUE TITLE
AnomalyDX10\AVX hung on loadin

### ISSUE THREAD

**Issue by porkmanager** [themrdemonized/STALKER-Anomaly-modded-exes#60]
STALKER-Anomaly-modded-exes_2023.12.17 R3 renders doesn't load the game. Its hunging on end loadscreen "press any key..."

**Comment by themrdemonized** [comment]
Works ok on my side

**Comment by porkmanager** [comment]
Sry 4 dat report. That was my fault. Something was dropped into my gaydata folder.
