### ISSUE TITLE
Conflict With hard coded rectangle mini map

### ISSUE THREAD

**Issue by Timo2024** [themrdemonized/STALKER-Anomaly-modded-exes#61]
Hey buddy, is it possible to separate the current hard coded mini map change to either a menu option or as an optional ltx/script file? as it conflicts with SquareDOV (square minimap) - RavenAscendant 
Thanks for everything you do!
![AnomalyDX11AVX_FHCg2evK4o](https://github.com/themrdemonized/STALKER-Anomaly-modded-exes/assets/45249414/ad69391d-7972-4d5a-95f6-191f791dafbc)
![AnomalyDX11AVX_l7QCy0lg93](https://github.com/themrdemonized/STALKER-Anomaly-modded-exes/assets/45249414/926f4524-6fee-4864-9260-bb6b9df2be8b)

**Comment by themrdemonized** [comment]
Alright, i'll see what can be done about it

**Comment by themrdemonized** [comment]
Fixed in 2023.12.24
