### ISSUE TITLE
DXML not loading `eng` and `rus` localization files

### ISSUE THREAD

**Issue by augustsaintfreytag** [themrdemonized/STALKER-Anomaly-modded-exes#62]
According to the DXML documentation, quote, "DXML won't process translation strings other than from eng/rus folders", that reads like it indeed does load and process localization XML files like `text/eng/ui_st_inventory.xml`. However, logging all files loaded by DXML during launch (and an F2 debug game), these files do not run through DXML or the `on_xml_read` callback is never called for these. Patching text that appears in the details/stats panel for items would require it, though, like `ui_ammo_types`.

Is this a bug? Is the documentation wrong about it and DXML does not process localization files (all the `*st*` files) at all?

Interestingly enough, the documentation says the module won't process character files and those are the ones specifically handled in the *Additional Functions* section, though the callback does get invoked for `gameplay\character_desc_marsh.xml` and others.

**Comment by themrdemonized** [comment]
it does work for localization files, otherwise you wouldn't see `Modified exes` line in the title screen, it is modified by `modxml_test.script`

**Comment by augustsaintfreytag** [comment]
Hm, that is true. But checking the sample code of the test script, I can't see where I could've gone wrong.

Assuming I write a script like the following:

```lua
function on_xml_read()
	RegisterScriptCallback("on_xml_read", function(xml_scope_name, xml_obj)
		printf("DXML callback called for file '%s'.", xml_scope_name)
	end)
end
```

Shouldn't that log the name of all localized string files, too? In this case, my file was named `modxml_ui_text_auto_patcher.script`, by what I got from the documentation, all that's required is that the LUA script name leads withs `modxml`.

Some XML files run through this and their names get logged but notably not a single `ui_st` file. If I use this script, load a debug game, open my inventory, I see strings defined in `ui_st_inventory.xml` but the file name is never logged. Interestingly enough, `_game_version.xml` is also not logged and DXML does not appear in the bottom row if it's supposed to. Another mod I'm building that only patches UI files through DXML works flawlessly.

<img width="719" alt="Screenshot 2024-01-06 181749" src="https://github.com/themrdemonized/STALKER-Anomaly-modded-exes/assets/7656669/914aaec9-a397-4d47-8b42-40eb283194bc">

**Comment by themrdemonized** [comment]
![изображение](https://github.com/themrdemonized/STALKER-Anomaly-modded-exes/assets/46323442/9b3b3e54-1cc5-4644-a6ae-888f6cd74c6c)
works fine for me

**Comment by augustsaintfreytag** [comment]
I see, thanks for testing it out. DXML itself is implemented in the modified executables, right? I'm going to try to swap them out and see what changes, I don't see how else part of the GAMMA modpack would interfere with XML loading. I greatly appreciate your work, none of the mods I'm working on would be possible without what you've done, so thank you.
