### ISSUE TITLE
feaure request: add key for primary weapons swap

### ISSUE THREAD

**Issue by BlackburnUTG** [themrdemonized/STALKER-Anomaly-modded-exes#63]
So if you have “weapon a” and “weapon b” in your main slots 2 and 3 - you dont need to remember what key you need to press for switching from “weapon a” to “weapon b”.
and perhaps add key for holster curent weapon - is good idea too

**Comment by themrdemonized** [comment]
this can be done with a mod, no engine edit is required. You have to find a modder to do it though
