### ISSUE TITLE
SymGetSymFromAddr64 fails with ERROR_NO_MORE_FILES

### ISSUE THREAD

**Issue by lionkor** [themrdemonized/STALKER-Anomaly-modded-exes#64]
When running the latest release in Wine, it crashes due to the error in the title. Log attached: 
[xray_lion.log](https://github.com/themrdemonized/STALKER-Anomaly-modded-exes/files/13890240/xray_lion.log)

The fix is to use an older version. I went back just a few versions, 2023.12.02 happened to work.

**Comment by themrdemonized** [comment]
Fixed in 2024.01.11
