### ISSUE TITLE
Crash when killing a mutant

### ISSUE THREAD

**Issue by billlcarr** [themrdemonized/STALKER-Anomaly-modded-exes#65]
Just started getting this crash that seems to occur randomly when killing a mutant with a scoped weapon. The log file ends with the following:

SymInit: Symbol-SearchPath: '.;G:\Games\STALKER - Anomaly;G:\Games\STALKER - Anomaly\bin;C:\WINDOWS;C:\WINDOWS\system32;', symOptions: 530, UserName: 'Dreamhive'
OS-Version: 6.2.9200 () 0x300-0x1
G:\Games\STALKER - Anomaly\bin\AnomalyDX11AVX.exe:AnomalyDX11AVX.exe (0000000140000000), size: 16105472 (result: 0), SymType: '-exported-', PDB: 'G:\Games\STALKER - Anomaly\bin\AnomalyDX11AVX.exe'
ERROR: SymGetSymFromAddr64, GetLastError: 487 (Address: 00000001400C6D32)
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00000001400C6D32)
00000001400C6D32 (AnomalyDX11AVX): (filename not available): (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 487 (Address: 0000000140090D8D)
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 0000000140090D8D)
0000000140090D8D (AnomalyDX11AVX): (filename not available): (function-name not available)
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FF91113C90C)
00007FF91113C90C (KERNELBASE): (filename not available): UnhandledExceptionFilter
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FF913838ABD)
00007FF913838ABD (ntdll): (filename not available): memcpy
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FF91381F197)
00007FF91381F197 (ntdll): (filename not available): _C_specific_handler
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FF91383441F)
00007FF91383441F (ntdll): (filename not available): _chkstk
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FF9137AE466)
00007FF9137AE466 (ntdll): (filename not available): RtlFindCharInUnicodeString
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FF91383340E)
00007FF91383340E (ntdll): (filename not available): KiUserExceptionDispatcher
ERROR: SymGetSymFromAddr64, GetLastError: 487 (Address: 0000000140123333)
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 0000000140123333)
0000000140123333 (AnomalyDX11AVX): (filename not available): (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 487 (Address: 00000001401A8FF4)
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00000001401A8FF4)
00000001401A8FF4 (AnomalyDX11AVX): (filename not available): (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 487 (Address: 00000001400F7BE5)
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00000001400F7BE5)
00000001400F7BE5 (AnomalyDX11AVX): (filename not available): (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 487 (Address: 00000001401B9ABE)
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00000001401B9ABE)
00000001401B9ABE (AnomalyDX11AVX): (filename not available): (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 487 (Address: 0000000140074A90)
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 0000000140074A90)
0000000140074A90 (AnomalyDX11AVX): (filename not available): (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 487 (Address: 00000001400753BE)
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00000001400753BE)
00000001400753BE (AnomalyDX11AVX): (filename not available): (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 487 (Address: 0000000140043CC7)
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 0000000140043CC7)
0000000140043CC7 (AnomalyDX11AVX): (filename not available): (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 487 (Address: 000000014012E408)
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 000000014012E408)
000000014012E408 (AnomalyDX11AVX): (filename not available): (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 487 (Address: 000000014002AC92)
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 000000014002AC92)
000000014002AC92 (AnomalyDX11AVX): (filename not available): (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 487 (Address: 000000014002A11B)
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 000000014002A11B)
000000014002A11B (AnomalyDX11AVX): (filename not available): (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 487 (Address: 000000014002B8DF)
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 000000014002B8DF)
000000014002B8DF (AnomalyDX11AVX): (filename not available): (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 487 (Address: 000000014002B10F)
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 000000014002B10F)
000000014002B10F (AnomalyDX11AVX): (filename not available): (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 487 (Address: 000000014007A625)
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 000000014007A625)
000000014007A625 (AnomalyDX11AVX): (filename not available): (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 487 (Address: 000000014007AEAD)
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 000000014007AEAD)
000000014007AEAD (AnomalyDX11AVX): (filename not available): (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 487 (Address: 000000014007D34B)
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 000000014007D34B)
000000014007D34B (AnomalyDX11AVX): (filename not available): (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 487 (Address: 000000014085043E)
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 000000014085043E)
000000014085043E (AnomalyDX11AVX): (filename not available): (function-name not available)
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FF911D4257D)
00007FF911D4257D (KERNEL32): (filename not available): BaseThreadInitThunk
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FF9137EAA58)
00007FF9137EAA58 (ntdll): (filename not available): RtlUserThreadStart
at address 0x0000000140123333

Any help is greatly appreciated.

**Comment by billlcarr** [comment]
By the way, I'm using the EXEs that come with the current version of SSS (if I try using the newest exes from here with SSS 19, I get a shader compilation error on start).

**Comment by themrdemonized** [comment]
download exes and pdbs from here https://github.com/themrdemonized/xray-monolith/releases/tag/2024.1.27
when you crash, upload log and mdmp file

**Comment by billlcarr** [comment]
[xray_dreamhive.log](https://github.com/themrdemonized/STALKER-Anomaly-modded-exes/files/14072105/xray_dreamhive.log)

**Comment by billlcarr** [comment]
Thank you. The log file and DMP are here-

https://drive.google.com/drive/folders/1ep4QNIbXTtJQ2Yp-WQOFo_W01NpM7ZqG?usp=sharing

**Comment by billlcarr** [comment]
Sorry, I must have accidentally closed this thread when I posted my last comment.

**Comment by billlcarr** [comment]
I should have also mentioned, I didn't get a shader compilation failure this time, so I'm using the most current EXEs now (the one you gave me the link to). As to the crash, in my current save I'm on the far end of the fire tunnel in Wild Territory, and there is a pack of dogs on the other side. Using the SVD Lynx with the scope, it will inevitably crash when killing one of the dogs. Not necessarily the first dog I kill (in a few tests I killed 2 or 3 before it finally crashed), but it always crashes on one of them.

**Comment by themrdemonized** [comment]
I can't reproduce the crash on the vanilla install, killing dogs with no issues

**Comment by billlcarr** [comment]
OK, thanks. Does the log have anything that might give me somewhere to start looking for what might be causing this?

**Comment by billlcarr** [comment]
I wonder if this could have something to do with the new "Weapon overheat script fix" add-on. That's the only thing I've added to my load order in forever. It modifies "item_weapon.script".

Anyway, thanks for your help. Going to keep testing. Any clues you can give me to get me on the right track are much appreciated.

**Comment by themrdemonized** [comment]
> OK, thanks. Does the log have anything that might give me somewhere to start looking for what might be causing this?

it has something to do with enemy detection feature of the scope, i assume the upgrade

**Comment by themrdemonized** [comment]
[VerifiedDX11.zip](https://github.com/themrdemonized/STALKER-Anomaly-modded-exes/files/14074001/VerifiedDX11.zip)

Try launching the game with this exe and drop the logs and mdmp when it crashes. it will run slower, no worries

**Comment by billlcarr** [comment]
Will do, thanks very much!

**Comment by billlcarr** [comment]
Here's the log and mdmp

https://drive.google.com/drive/folders/1zSCelC14_E2ObzfEiBD6AFGYxZWg96HZ?usp=sharing

**Comment by billlcarr** [comment]
With further testing, it seems to only happen when I kill a pseudo dog when using the scope. Also, I have the "Fixed detector scopes" add-on that makes that scope upgrade actually function, but it still crashed after removing the add-on.

**Comment by themrdemonized** [comment]
Nope, still works on vanilla. So there is a problem elsewhere that leads to this issue

**Comment by billlcarr** [comment]
Could something like this be caused by a corrupt save?

I started a new game in debug mode, spawned in a bunch of pseudo dogs and picked them off one by one using the scope on the SVD, and no crash. I tried it with and without the detector upgrade. Didn't disable any add-ons.

Is there a difference between mutants spawned with the debug menu and mutants that spawn organically?

**Comment by billlcarr** [comment]
This is weird. I did the same thing in debug mode on my save that's crashing. Spawned a bunch of pseudo dogs and killed them all with no crash. Went back to wild territory and started picking off the dogs from the other side of the fire tunnel, and boom, crash...

**Comment by billlcarr** [comment]
Happened again, this time in Cordon, and it was a pseudodog again. It seems to only be organic spawns the crash happens with, because I can spawn in pseudodogs with the debug menu all day and not crash at all killing them in the same way with the same gun.

Here are the logs, although I'm sure they're identical to the previous ones.

https://drive.google.com/drive/folders/1ASUleFIvqYmdvzWc9EAMYvErxlRengMW?usp=sharing

Could this be save corruption? I don't see how it could be an add-on, because I haven't changed my load order in over a year (other than updating newer add-ons as new versions are released). The only updates I've done recently are the helmet/mask animation mod, and the ledge grabbing/grappling mod, neither of which I can see causing something like this.

I'm going to start a new game and see if it happens again.

**Comment by billlcarr** [comment]
I'm going to close this. I think it was either a corrupt save, or that particular gun I was using was bugged. I started a new game and it hasn't happened since, even when  killing pseudodogs using the scope, so I'm pretty sure it was a bug in the save. Thanks very much for your time and all the amazing work you've done with this!
