### ISSUE TITLE
Extra letters in inventory 

### ISSUE THREAD

**Issue by pr0statitis** [themrdemonized/STALKER-Anomaly-modded-exes#68]
Howdy-ho! Feel free to close this if this has nothing to do with the modded exes. I'm just super curious as to why this happens.

When using the [Old World Addon](https://www.moddb.com/mods/stalker-anomaly/addons/152-old-world-addon) with the modded exes the status icons/bars in the inventory show extra "Bs" (look at the [screenshots](https://imgur.com/a/oT2ca7o)). 
What could the issues be? I just can't make any sense of this and I'm super intrigued as to what causes this.

**Comment by pr0statitis** [comment]
This is far from crucial, but just so curious to me, which is why I felt to report it both here and to the author of the Old World Addon

**Comment by themrdemonized** [comment]
i've never used old world so i have no idea, you need to ask the author of this mod
