### ISSUE TITLE
Проблемка нарисовалась

### ISSUE THREAD

**Issue by Cadob** [themrdemonized/STALKER-Anomaly-modded-exes#69]
Привет, Дефендер определяет девятый директ как троян. 

![image](https://github.com/themrdemonized/STALKER-Anomaly-modded-exes/assets/160486780/f9ed32ec-9ab4-41f1-b5cd-6a0669937812)

И жалуется он исключительно на девятку, никакой другой директ не под влиянием. Именно в тот момент когда я пытаюсь перекинуть файлы в папку, мне пишет что девятка заражена, потом начинает ругаться дефендер, показывает то 2 то 3 трояна за один раз, стоит принимать?

**Comment by themrdemonized** [comment]
https://www.virustotal.com/gui/file/ccc37f4fd075a7a92b0c5ea151932b320bf3ba3ce70bdf39e268d99144c1dae8/detection
чини свой комп
