### ISSUE TITLE
Weather settings have never seemed to work

### ISSUE THREAD

**Issue by billlcarr** [themrdemonized/STALKER-Anomaly-modded-exes#70]
The weather settings (where you choose the frequency and duration of the different weather variations) don't seem to have any noticeable effect (and it's been this way for as long as I've played Anomaly). No matter what I set, I still get cloudy or rainy/stormy 90% of the time. Is there another way to adjust the weather cycle that would actually work? Maybe in a config file somewhere? If not, is this something that could be fixed in the EXE? Thanks!

**Comment by themrdemonized** [comment]
check dynamic_weather_graphs.ltx and weathers folder in config

**Comment by billlcarr** [comment]
Hey, just wanted to say thanks. It looks like it might have been some edits Soundscape Overhaul made to dynamic_weather_graphs.ltx that weren't related to audio. I assume it was his personal edits that he left in the mod by mistake. Anyway, I replaced that section with the appropriate section from the vanilla file and I had sunny weather for the first time this week. So thank you!
