### ISSUE TITLE
SSS 20 exes don't render water.

### ISSUE THREAD

**Issue by I-Am-Everyday-People** [themrdemonized/STALKER-Anomaly-modded-exes#72]
February 28 exes work fine, but the three March versions make water completely transparent for dx10. Tested with no addons or mods and updated VSRedist C++. March dx11 versions have no issues, only dx10. Clips taken with dx10avx and mods enabled.
March exes

https://github.com/themrdemonized/STALKER-Anomaly-modded-exes/assets/163099589/d95b509c-4278-4d8a-808b-169e8578b303

February exes

https://github.com/themrdemonized/STALKER-Anomaly-modded-exes/assets/163099589/13697565-7d87-4375-902d-12ce4e767d41

**Comment by themrdemonized** [comment]
Try the latest version please

**Comment by I-Am-Everyday-People** [comment]
Perfect! Thank you.
