### ISSUE TITLE
A mistake when killing military men with weapons.

### ISSUE THREAD

**Issue by DedushkaSvyat** [themrdemonized/STALKER-Anomaly-modded-exes#73]
This error occurs when I create military units and start shooting at them

Here are the logs and the MDMP file: https://drive.google.com/drive/folders/1qhFGdn2Ap_Jfl94ckx-xT6B3EzDmAe7Q?usp=sharing

!WARNING : level.object_by_id(nil) called!
* [x-ray]: Full Memory Stats
* [win32]: free[137425040472 K], reserved[4692240 K], committed[9220696 K]
* [ D3D ]: textures[679001 K]
* [x-ray]: process heap[1541494 K]
* [x-ray]: economy: strings[114720 K], smem[198407 K]
* Saving spawns...
* Saving objects...
* 27594 objects are successfully saved
* Game teren - autosave.scop is successfully saved to file 'd:/games/sasalker/stalker/bin/..\appdata\savedgames\teren - autosave.scop'
[LSS] Spawning object [zombie_weak28487][zombie_weak][28487]
[LSS] Spawning object [zombie_normal28488][zombie_normal][28488]
[LSS] Spawning object [zombie_normal28489][zombie_normal][28489]
[LSS] Spawning object [sim_default_zombied_028495][sim_default_zombied_0][28495]
[LSS] Spawning object [sim_default_zombied_028498][sim_default_zombied_0][28498]
[LSS] Spawning object [sim_default_zombied_028501][sim_default_zombied_0][28501]
[LSS] Spawning object [sim_default_zombied_028504][sim_default_zombied_0][28504]
[LSS] Spawning object [sim_default_zombied_128508][sim_default_zombied_1][28508]
[LSS] Spawning object [sim_default_zombied_028511][sim_default_zombied_0][28511]
[LSS] Spawning object [sim_default_zombied_028514][sim_default_zombied_0][28514]
[LSS] Spawning object [zombie_weak28523][zombie_weak][28523]
[LSS] Spawning object [zombie_weak28524][zombie_weak][28524]
[LSS] Spawning object [zombie_strong28525][zombie_strong][28525]
[LSS] Spawning object [sim_default_zombied_328527][sim_default_zombied_3][28527]
[LSS] Spawning object [sim_default_zombied_428530][sim_default_zombied_4][28530]
[LSS] Spawning object [sim_default_zombied_428533][sim_default_zombied_4][28533]
[LSS] Spawning object [sim_default_zombied_228536][sim_default_zombied_2][28536]
[LSS] Spawning object [sim_default_zombied_228540][sim_default_zombied_2][28540]
[LSS] Spawning object [sim_default_zombied_328543][sim_default_zombied_3][28543]
[LSS] Spawning object [sim_default_zombied_228546][sim_default_zombied_2][28546]
[LSS] Spawning object [zombie_weak28560][zombie_weak][28560]
[LSS] Spawning object [zombie_strong28561][zombie_strong][28561]
[LSS] Spawning object [zombie_weak28562][zombie_weak][28562]
[LSS] Spawning object [zombie_strong28563][zombie_strong][28563]
[LSS] Spawning object [sim_default_zombied_028565][sim_default_zombied_0][28565]
[LSS] Spawning object [sim_default_zombied_028568][sim_default_zombied_0][28568]
[LSS] Spawning object [sim_default_zombied_028571][sim_default_zombied_0][28571]
[LSS] Spawning object [zombie_strong28575][zombie_strong][28575]
[LSS] Spawning object [zombie_weak28576][zombie_weak][28576]
[LSS] Spawning object [zombie_weak28577][zombie_weak][28577]
[LSS] Spawning object [zombie_strong28579][zombie_strong][28579]
[LSS] Spawning object [zombie_normal28580][zombie_normal][28580]
[LSS] Spawning object [zombie_weak28581][zombie_weak][28581]
[LSS] Spawning object [zombie_weak28582][zombie_weak][28582]
[LSS] Spawning object [sim_default_zombied_028584][sim_default_zombied_0][28584]
[LSS] Spawning object [sim_default_zombied_028587][sim_default_zombied_0][28587]
[LSS] Spawning object [sim_default_zombied_028590][sim_default_zombied_0][28590]
[LSS] Spawning object [zombie_normal28594][zombie_normal][28594]
[LSS] Spawning object [zombie_weak28595][zombie_weak][28595]
[LSS] Spawning object [zombie_strong28596][zombie_strong][28596]
[LSS] Spawning object [zombie_weak28598][zombie_weak][28598]
[LSS] Spawning object [zombie_weak28599][zombie_weak][28599]
[LSS] Spawning object [zombie_strong28600][zombie_strong][28600]
[LSS] Spawning object [zombie_weak28613][zombie_weak][28613]
[LSS] Spawning object [zombie_weak28614][zombie_weak][28614]
[LSS] Spawning object [zombie_normal28615][zombie_normal][28615]
[LSS] Spawning object [zombie_normal28616][zombie_normal][28616]
[LSS] Spawning object [sim_default_zombied_228618][sim_default_zombied_2][28618]
[LSS] Spawning object [sim_default_zombied_228621][sim_default_zombied_2][28621]
[LSS] Spawning object [sim_default_zombied_128624][sim_default_zombied_1][28624]
[LSS] Spawning object [sim_default_zombied_228627][sim_default_zombied_2][28627]
[LSS] Spawning object [zone_mine_vapour28630][zone_mine_vapour][28630]
[LSS] Spawning object [zone_mine_vapour28631][zone_mine_vapour][28631]
[LSS] Spawning object [zone_mine_vapour28632][zone_mine_vapour][28632]
[LSS] Spawning object [zone_mine_electric_weak28633][zone_mine_electric_weak][28633]
[LSS] Spawning object [zone_mine_electric_weak28634][zone_mine_electric_weak][28634]
[LSS] Spawning object [zone_mine_electric_weak28635][zone_mine_electric_weak][28635]
[LSS] Spawning object [zone_mine_electric_weak28636][zone_mine_electric_weak][28636]
[LSS] Spawning object [zone_mine_electric_weak28637][zone_mine_electric_weak][28637]
[LSS] Spawning object [zone_mine_electric_weak28638][zone_mine_electric_weak][28638]
[LSS] Spawning object [zone_mine_electric_weak28639][zone_mine_electric_weak][28639]
[LSS] Spawning object [zone_mine_electric_weak28640][zone_mine_electric_weak][28640]
[LSS] Spawning object [zone_mine_shatterpoint28641][zone_mine_shatterpoint][28641]
[LSS] Spawning object [zone_mine_shatterpoint28642][zone_mine_shatterpoint][28642]
[LSS] Spawning object [zone_mine_shatterpoint28643][zone_mine_shatterpoint][28643]
[LSS] Spawning object [zone_mine_shatterpoint28644][zone_mine_shatterpoint][28644]
[LSS] Spawning object [zone_mine_thermal_weak28645][zone_mine_thermal_weak][28645]
[LSS] Spawning object [zone_mine_thermal_weak28646][zone_mine_thermal_weak][28646]
[LSS] Spawning object [zone_mine_thermal_weak28647][zone_mine_thermal_weak][28647]
[LSS] Spawning object [zone_radioactive_weak28648][zone_radioactive_weak][28648]
[LSS] Spawning object [zone_radioactive_weak28649][zone_radioactive_weak][28649]
[LSS] Spawning object [zone_radioactive_weak28650][zone_radioactive_weak][28650]
[LSS] Spawning object [zone_radioactive_weak28651][zone_radioactive_weak][28651]
[LSS] Spawning object [zone_radioactive_weak28652][zone_radioactive_weak][28652]
[LSS] Spawning object [zone_radioactive_weak28653][zone_radioactive_weak][28653]
[LSS] Spawning object [zone_radioactive_weak28654][zone_radioactive_weak][28654]
[LSS] Spawning object [af_fire_loop28655][af_fire_loop][28655]
[LSS] Spawning object [af_cell28656][af_cell][28656]
[LSS] Spawning object [m_crow28672][m_crow][28672]
[LSS] Spawning object [m_crow28928][m_crow][28928]
[LSS] Spawning object [m_crow29184][m_crow][29184]
intro_start game_loaded
* [x-ray]: Handled Necessary Textures Destruction
* MEMORY USAGE: 1591315 K
* End of synchronization A[1] R[1]
intro_delete ::update_game_loaded
[LSS] Spawning object [zombie_weak28518][zombie_weak][28518]
[LSS] Spawning object [zombie_strong28519][zombie_strong][28519]
[LSS] Spawning object [zombie_strong28520][zombie_strong][28520]
[LSS] Spawning object [zombie_normal28521][zombie_normal][28521]
! Fallback to default bump map: arm\arm_bnd_tr_bump#
* loading script scopeRadii.script
* [x-ray]: Full Memory Stats
* [win32]: free[137424791412 K], reserved[4660932 K], committed[9501064 K]
* [ D3D ]: textures[819091 K]
* [x-ray]: process heap[1609225 K]
* [x-ray]: economy: strings[115341 K], smem[281545 K]
[LSS] Spawning object [sim_default_military_429721][sim_default_military_4][29721]
[LSS] Spawning object [sim_default_military_329726][sim_default_military_3][29726]
[LSS] Spawning object [sim_default_military_329731][sim_default_military_3][29731]
[LSS] Spawning object [zombie_normal28491][zombie_normal][28491]
[LSS] Spawning object [zombie_strong28492][zombie_strong][28492]
[LSS] Spawning object [zombie_strong28493][zombie_strong][28493]
~ cannot remove restriction with id [7965][pri_b307_zone_mine_thermal_average] to the entity with id [28577][zombie_weak28577], because it is not added
stack trace:

 

SymInit: Symbol-SearchPath: '.;D:\games\SASALKER\stalker\bin;D:\games\SASALKER\stalker\bin;C:\Windows;C:\Windows\system32;', symOptions: 530, UserName: 'teren'
OS-Version: 6.2.9200 () 0x300-0x1
D:\games\SASALKER\stalker\bin\AnomalyDX11.exe:AnomalyDX11.exe (0000000140000000), size: 18173952 (result: 0), SymType: '-exported-', PDB: 'D:\games\SASALKER\stalker\bin\AnomalyDX11.exe'
at address 0x00000001403E0E23

**Comment by DedushkaSvyat** [comment]
* [x-ray]: Full Memory Stats
* [win32]: free[137425108320 K], reserved[4705292 K], committed[9139796 K]
* [ D3D ]: textures[666788 K]
* [x-ray]: process heap[1531616 K]
* [x-ray]: economy: strings[113751 K], smem[199833 K]
* Saving spawns...
* Saving objects...
* 27527 objects are successfully saved
* Game teren - autosave.scop is successfully saved to file 'd:/games/sasalker/stalker/bin/..\appdata\savedgames\teren - autosave.scop'
[LSS] Spawning object [zombie_strong28658][zombie_strong][28658]
[LSS] Spawning object [zombie_weak28659][zombie_weak][28659]
[LSS] Spawning object [zombie_strong28660][zombie_strong][28660]
[LSS] Spawning object [zombie_weak28661][zombie_weak][28661]
[LSS] Spawning object [zombie_weak28668][zombie_weak][28668]
[LSS] Spawning object [zombie_normal28669][zombie_normal][28669]
[LSS] Spawning object [zombie_weak28670][zombie_weak][28670]
[LSS] Spawning object [zombie_weak28672][zombie_weak][28672]
[LSS] Spawning object [zombie_strong28673][zombie_strong][28673]
[LSS] Spawning object [zombie_normal28674][zombie_normal][28674]
[LSS] Spawning object [sim_default_zombied_228676][sim_default_zombied_2][28676]
[LSS] Spawning object [sim_default_zombied_228679][sim_default_zombied_2][28679]
[LSS] Spawning object [sim_default_zombied_228682][sim_default_zombied_2][28682]
[LSS] Spawning object [sim_default_zombied_328685][sim_default_zombied_3][28685]
[LSS] Spawning object [zombie_normal28689][zombie_normal][28689]
[LSS] Spawning object [zombie_strong28690][zombie_strong][28690]
[LSS] Spawning object [zombie_weak28691][zombie_weak][28691]
[LSS] Spawning object [zombie_normal28692][zombie_normal][28692]
[LSS] Spawning object [zombie_weak28694][zombie_weak][28694]
[LSS] Spawning object [zombie_normal28695][zombie_normal][28695]
[LSS] Spawning object [zombie_strong28696][zombie_strong][28696]
[LSS] Spawning object [zombie_weak28697][zombie_weak][28697]
[LSS] Spawning object [zombie_strong28699][zombie_strong][28699]
[LSS] Spawning object [zombie_weak28700][zombie_weak][28700]
[LSS] Spawning object [zombie_normal28701][zombie_normal][28701]
[LSS] Spawning object [zombie_weak28703][zombie_weak][28703]
[LSS] Spawning object [zombie_normal28704][zombie_normal][28704]
[LSS] Spawning object [zombie_weak28705][zombie_weak][28705]
[LSS] Spawning object [zombie_strong28712][zombie_strong][28712]
[LSS] Spawning object [zombie_normal28713][zombie_normal][28713]
[LSS] Spawning object [zombie_weak28714][zombie_weak][28714]
[LSS] Spawning object [zombie_strong28715][zombie_strong][28715]
[LSS] Spawning object [sim_default_zombied_228717][sim_default_zombied_2][28717]
[LSS] Spawning object [sim_default_zombied_128720][sim_default_zombied_1][28720]
[LSS] Spawning object [sim_default_zombied_228723][sim_default_zombied_2][28723]
[LSS] Spawning object [sim_default_zombied_128726][sim_default_zombied_1][28726]
[LSS] Spawning object [sim_default_zombied_128730][sim_default_zombied_1][28730]
[LSS] Spawning object [sim_default_zombied_228733][sim_default_zombied_2][28733]
[LSS] Spawning object [sim_default_zombied_128736][sim_default_zombied_1][28736]
[LSS] Spawning object [zombie_normal28753][zombie_normal][28753]
[LSS] Spawning object [zombie_strong28754][zombie_strong][28754]
[LSS] Spawning object [zombie_normal28755][zombie_normal][28755]
[LSS] Spawning object [zombie_weak28762][zombie_weak][28762]
[LSS] Spawning object [zombie_weak28763][zombie_weak][28763]
[LSS] Spawning object [zombie_normal28764][zombie_normal][28764]
[LSS] Spawning object [zombie_weak28765][zombie_weak][28765]
[LSS] Spawning object [zombie_strong28767][zombie_strong][28767]
[LSS] Spawning object [zombie_weak28768][zombie_weak][28768]
[LSS] Spawning object [zombie_strong28769][zombie_strong][28769]
[LSS] Spawning object [zombie_strong28770][zombie_strong][28770]
[LSS] Spawning object [zone_mine_shatterpoint28771][zone_mine_shatterpoint][28771]
[LSS] Spawning object [zone_mine_shatterpoint28772][zone_mine_shatterpoint][28772]
[LSS] Spawning object [zone_mine_shatterpoint28773][zone_mine_shatterpoint][28773]
[LSS] Spawning object [zone_mine_shatterpoint28774][zone_mine_shatterpoint][28774]
[LSS] Spawning object [zone_mine_gravitational_average28775][zone_mine_gravitational_average][28775]
[LSS] Spawning object [zone_mine_gravitational_average28776][zone_mine_gravitational_average][28776]
[LSS] Spawning object [zone_mine_gravitational_average28777][zone_mine_gravitational_average][28777]
[LSS] Spawning object [zone_mine_gravitational_average28778][zone_mine_gravitational_average][28778]
[LSS] Spawning object [zone_mine_gravitational_average28779][zone_mine_gravitational_average][28779]
[LSS] Spawning object [zone_mine_gravitational_average28780][zone_mine_gravitational_average][28780]
[LSS] Spawning object [zone_mine_gravitational_average28781][zone_mine_gravitational_average][28781]
[LSS] Spawning object [zone_mine_gravitational_average28782][zone_mine_gravitational_average][28782]
[LSS] Spawning object [zone_field_radioactive_average28783][zone_field_radioactive_average][28783]
[LSS] Spawning object [zone_field_radioactive_average28784][zone_field_radioactive_average][28784]
[LSS] Spawning object [zone_field_radioactive_average28785][zone_field_radioactive_average][28785]
[LSS] Spawning object [zone_field_radioactive_average28786][zone_field_radioactive_average][28786]
[LSS] Spawning object [zone_field_radioactive_average28787][zone_field_radioactive_average][28787]
[LSS] Spawning object [zone_field_radioactive_average28788][zone_field_radioactive_average][28788]
[LSS] Spawning object [zone_field_radioactive_average28789][zone_field_radioactive_average][28789]
[LSS] Spawning object [zone_mine_gravitational_average28790][zone_mine_gravitational_average][28790]
[LSS] Spawning object [zone_mine_gravitational_average28791][zone_mine_gravitational_average][28791]
[LSS] Spawning object [zone_mine_gravitational_average28792][zone_mine_gravitational_average][28792]
[LSS] Spawning object [zone_mine_gravitational_average28793][zone_mine_gravitational_average][28793]
[LSS] Spawning object [zone_mine_umbra28794][zone_mine_umbra][28794]
[LSS] Spawning object [zone_mine_umbra28795][zone_mine_umbra][28795]
[LSS] Spawning object [zone_mine_umbra28796][zone_mine_umbra][28796]
[LSS] Spawning object [zone_mine_umbra28797][zone_mine_umbra][28797]
[LSS] Spawning object [zone_mine_umbra28798][zone_mine_umbra][28798]
[LSS] Spawning object [zone_mine_umbra28799][zone_mine_umbra][28799]
[LSS] Spawning object [zone_mine_springboard28800][zone_mine_springboard][28800]
[LSS] Spawning object [zone_mine_springboard28801][zone_mine_springboard][28801]
[LSS] Spawning object [zone_mine_springboard28802][zone_mine_springboard][28802]
[LSS] Spawning object [zone_mine_springboard28803][zone_mine_springboard][28803]
[LSS] Spawning object [zone_radioactive_weak28804][zone_radioactive_weak][28804]
[LSS] Spawning object [zone_radioactive_weak28805][zone_radioactive_weak][28805]
[LSS] Spawning object [zone_radioactive_weak28806][zone_radioactive_weak][28806]
[LSS] Spawning object [zone_radioactive_weak28807][zone_radioactive_weak][28807]
[LSS] Spawning object [zone_radioactive_weak28808][zone_radioactive_weak][28808]
[LSS] Spawning object [af_zhelch28809][af_zhelch][28809]
[LSS] Spawning object [af_glass28810][af_glass][28810]
[LSS] Spawning object [af_death_lamp28811][af_death_lamp][28811]
! Missing ogg-comment, file:  d:/games/sasalker/stalker/bin/..\gamedata\sounds\weapons\bm16\bm16_reload_lr.ogg
! Missing ogg-comment, file:  d:/games/sasalker/stalker/bin/..\gamedata\sounds\weapons\bm16\bm16_reload_l.ogg
[LSS] Spawning object [m_crow28928][m_crow][28928]
[LSS] Spawning object [m_crow29184][m_crow][29184]
[LSS] Spawning object [m_crow29440][m_crow][29440]
intro_start game_loaded
* [x-ray]: Handled Necessary Textures Destruction
* MEMORY USAGE: 1576355 K
* End of synchronization A[1] R[1]
intro_delete ::update_game_loaded
! Fallback to default bump map: arm\arm_bnd_tr_bump#
[LSS] Spawning object [sim_default_military_329738][sim_default_military_3][29738]
[LSS] Spawning object [sim_default_military_429743][sim_default_military_4][29743]
[LSS] Spawning object [sim_default_military_429748][sim_default_military_4][29748]
[LSS] Spawning object [sim_default_military_329753][sim_default_military_3][29753]
[LSS] Spawning object [sim_default_military_329957][sim_default_military_3][29957]
[LSS] Spawning object [sim_default_military_329962][sim_default_military_3][29962]
[LSS] Spawning object [sim_default_military_429967][sim_default_military_4][29967]
* loading script scopeRadii.script
[LSS] Spawning object [zombie_weak28757][zombie_weak][28757]
[LSS] Spawning object [zombie_strong28758][zombie_strong][28758]
[LSS] Spawning object [zombie_normal28759][zombie_normal][28759]
[LSS] Spawning object [zombie_weak28760][zombie_weak][28760]
[LSS] Spawning object [prt_o_ballistic_1725971][prt_o_ballistic_17][25971]
[LSS] Spawning object [e_syringe25490][e_syringe][25490]
stack trace:

 

SymInit: Symbol-SearchPath: '.;D:\games\SASALKER\stalker\bin;D:\games\SASALKER\stalker\bin;C:\Windows;C:\Windows\system32;', symOptions: 530, UserName: 'teren'
OS-Version: 6.2.9200 () 0x300-0x1
D:\games\SASALKER\stalker\bin\AnomalyDX11.exe:AnomalyDX11.exe (0000000140000000), size: 18079744 (result: 0), SymType: 'PDB', PDB: '.\AnomalyDX11.pdb'
D:\a\xray-monolith\xray-monolith\src\xrCore\xrDebugNew.cpp (123): LogStackTrace
D:\a\xray-monolith\xray-monolith\src\xrCore\xrDebugNew.cpp (811): UnhandledFilter
D:\a\xray-monolith\xray-monolith\src\xrGame\stalker_movement_manager_obstacles.cpp (180): stalker_movement_manager_obstacles::move_along_path
D:\a\xray-monolith\xray-monolith\src\xrGame\stalker_movement_manager_smart_cover.cpp (169): stalker_movement_manager_smart_cover::on_frame
D:\a\xray-monolith\xray-monolith\src\xrGame\CustomMonster.cpp (582): CCustomMonster::UpdatePositionAnimation
D:\a\xray-monolith\xray-monolith\src\xrGame\CustomMonster.cpp (540): CCustomMonster::UpdateCL
D:\a\xray-monolith\xray-monolith\src\xrGame\Ai\Stalker\ai_stalker.cpp (1041): CAI_Stalker::UpdateCL
D:\a\xray-monolith\xray-monolith\src\xrEngine\xr_object_list.cpp (136): CObjectList::SingleUpdate
D:\a\xray-monolith\xray-monolith\src\xrEngine\xr_object_list.cpp (266): CObjectList::Update
D:\a\xray-monolith\xray-monolith\src\xrEngine\IGame_Level.cpp (194): IGame_Level::OnFrame
D:\a\xray-monolith\xray-monolith\src\xrGame\Level.cpp (646): CLevel::OnFrame
D:\a\xray-monolith\xray-monolith\src\xrEngine\pure.h (106): CRegistrator<pureFrame>::Process
D:\a\xray-monolith\xray-monolith\src\xrEngine\device.cpp (557): CRenderDevice::FrameMove
D:\a\xray-monolith\xray-monolith\src\xrEngine\device.cpp (322): CRenderDevice::on_idle
D:\a\xray-monolith\xray-monolith\src\xrEngine\device.cpp (498): CRenderDevice::Run
D:\a\xray-monolith\xray-monolith\src\xrEngine\x_ray.cpp (612): Startup
D:\a\xray-monolith\xray-monolith\src\xrEngine\x_ray.cpp (1108): WinMain_impl
D:\a\xray-monolith\xray-monolith\src\xrEngine\x_ray.cpp (1177): WinMain
at address 0x00000001403DBD03

**Comment by themrdemonized** [comment]
From the log there is some kind of a problem with pathfinding, specifically checking the doors. I guess spawn them in a different place, can't help with that further
