### ISSUE TITLE
SymInit: Symbol-SearchPath: - Crash Random

### ISSUE THREAD

**Issue by groovesharck** [themrdemonized/STALKER-Anomaly-modded-exes#74]
Had not had this crash since updating to 2024 Modded Exe's (Feb/March).

Started the game and crashed when i went to sleep with this error

(Saw a comment about this and tried the work-around suggested, ie "update/reinstall openal, Use STALKER-Anomaly-modded-exes_DX11-AVX_pdb,..".)
Still crashed.

any help appreciated <3

-----------------------------------
 Found commandline file!
Initializing File System...
using fs-ltx ../fsgame.ltx
File System Ready...
FS: 100471 files cached 81 archives, 20950Kb memory used.
Init FileSystem 21.140854 sec
'xrCore' build 9171, Mar 18 2024

Modded exes version 20240318

Game started: 22.03.2024 11:49:45.396

SymInit: Symbol-SearchPath: '.;I:\gabba\bin;I:\gabba\bin;C:\WINDOWS;C:\WINDOWS\system32;', symOptions: 530, UserName: 'bumbl'
OS-Version: 6.2.9200 () 0x100-0x1
I:\gabba\bin\AnomalyDX11AVX.exe:AnomalyDX11AVX.exe (0000000140000000), size: 18075648 (result: 0), SymType: 'PDB', PDB: '.\AnomalyDX11AVX.pdb'
D:\a\xray-monolith\xray-monolith\src\xrCore\xrDebugNew.cpp (123): LogStackTrace
D:\a\xray-monolith\xray-monolith\src\xrCore\xrDebugNew.cpp (811): UnhandledFilter
D:\a\xray-monolith\xray-monolith\src\xrGame\script_game_object_use.cpp (95): CScriptGameObject::Name
D:\a\xray-monolith\xray-monolith\sdk\include\boost\function\function_template.hpp (117): boost::detail::function::function_obj_invoker1<luabind::detail::mem_fn_callback<char const * (__cdecl CScriptGameObject::*)(void)const ,CScriptGameObject,luabind::detail::null_type>,int,lua_State *>::invoke
D:\a\xray-monolith\xray-monolith\src\3rd party\luabind\src\class_rep.cpp (727): luabind::detail::class_rep::function_dispatcher
D:\a\xray-monolith\xray-monolith\src\3rd party\luabind\src\pcall.cpp (42): luabind::detail::pcall
D:\a\xray-monolith\xray-monolith\src\xrGame\alife_storage_manager.cpp (75): CALifeStorageManager::save
D:\a\xray-monolith\xray-monolith\src\xrGame\game_sv_single.cpp (247): game_sv_Single::save_game
D:\a\xray-monolith\xray-monolith\src\xrGame\xrServer.cpp (596): xrServer::OnMessage
D:\a\xray-monolith\xray-monolith\src\xrGame\Level_network.cpp (299): CLevel::Send
D:\a\xray-monolith\xray-monolith\src\xrGame\console_commands.cpp (818): CCC_ALifeSave::Execute
D:\a\xray-monolith\xray-monolith\src\xrEngine\XR_IOConsole.cpp (638): CConsole::ExecuteCommand
D:\a\xray-monolith\xray-monolith\sdk\include\boost\function\function_template.hpp (117): boost::detail::function::function_obj_invoker1<luabind::detail::mem_fn_callback<void (__cdecl CConsole::*)(char const *),CConsole,luabind::detail::null_type>,int,lua_State *>::invoke
D:\a\xray-monolith\xray-monolith\src\3rd party\luabind\src\class_rep.cpp (727): luabind::detail::class_rep::function_dispatcher
D:\a\xray-monolith\xray-monolith\src\3rd party\luabind\src\pcall.cpp (42): luabind::detail::pcall
D:\a\xray-monolith\xray-monolith\src\xrGame\ActorEffector_script.cpp (27): CAnimatorCamEffectorScriptCB::Valid
D:\a\xray-monolith\xray-monolith\src\xrGame\ActorEffector.cpp (189): CAnimatorCamEffector::ProcessCam
D:\a\xray-monolith\xray-monolith\src\xrGame\ActorEffector.cpp (495): CActorCameraManager::ProcessCameraEffector
D:\a\xray-monolith\xray-monolith\src\xrEngine\CameraManager.cpp (379): CCameraManager::UpdateCamEffectors
D:\a\xray-monolith\xray-monolith\src\xrGame\ActorEffector.cpp (469): CActorCameraManager::UpdateCamEffectors
D:\a\xray-monolith\xray-monolith\src\xrEngine\CameraManager.cpp (351): CCameraManager::Update
D:\a\xray-monolith\xray-monolith\src\xrGame\ActorCameras.cpp (649): CActor::cam_Update
D:\a\xray-monolith\xray-monolith\src\xrGame\Actor.cpp (1147): CActor::UpdateCL
D:\a\xray-monolith\xray-monolith\src\xrEngine\xr_object_list.cpp (136): CObjectList::SingleUpdate
D:\a\xray-monolith\xray-monolith\src\xrEngine\xr_object_list.cpp (266): CObjectList::Update
D:\a\xray-monolith\xray-monolith\src\xrEngine\IGame_Level.cpp (194): IGame_Level::OnFrame
D:\a\xray-monolith\xray-monolith\src\xrGame\Level.cpp (646): CLevel::OnFrame
D:\a\xray-monolith\xray-monolith\src\xrEngine\pure.h (106): CRegistrator<pureFrame>::Process
D:\a\xray-monolith\xray-monolith\src\xrEngine\device.cpp (557): CRenderDevice::FrameMove
D:\a\xray-monolith\xray-monolith\src\xrEngine\device.cpp (322): CRenderDevice::on_idle
D:\a\xray-monolith\xray-monolith\src\xrEngine\device.cpp (498): CRenderDevice::Run
D:\a\xray-monolith\xray-monolith\src\xrEngine\x_ray.cpp (612): Startup
D:\a\xray-monolith\xray-monolith\src\xrEngine\x_ray.cpp (1108): WinMain_impl
D:\a\xray-monolith\xray-monolith\src\xrEngine\x_ray.cpp (1177): WinMain
 
[error][      87] : The parameter is incorrect.

at address 0x00000001403212FB

**Comment by themrdemonized** [comment]
please post the full log

**Comment by themrdemonized** [comment]
the error refers to script game objects, so its an issue on a script side. Unfortunately it's impossible to tell which script is failing. Check your mods. There is a lot of ArtiGrok messages, whatever that is. Start addressing with this.  Since it's not related to modded exes directly, I'm closing the issue
