### ISSUE TITLE
random crash of unknown cause

### ISSUE THREAD

**Issue by billlcarr** [themrdemonized/STALKER-Anomaly-modded-exes#75]
[xray_dreamhive.log](https://github.com/themrdemonized/STALKER-Anomaly-modded-exes/files/14731849/xray_dreamhive.log)

Had a crash happen today when I was in Garbage, and I can't tell from the log what caused it. It happened right as a loner was firing at a bandit near the train hangar. I reloaded the autosave generated on entering the level, and it didn't happen again. The odds are it's not related to the modded EXEs, and it doesn't seem easily repeatable, but I thought maybe you could tell from the attached log what might have caused it. I also have the MDMP file, if that would help let me know. Thanks!

**Comment by themrdemonized** [comment]
please upload that mdmp file

**Comment by billlcarr** [comment]
Sure thing, here's a google drive link to it.

https://drive.google.com/file/d/1DM9XYMndna8ZIVAEJxcSE-7LvyFYRAhx/view?usp=sharing

**Comment by themrdemonized** [comment]
the problem is with stalkers' AI, the problem is too complicated for me to understand, something with action planner. Can't fix it for now

**Comment by billlcarr** [comment]
No problem, it seems pretty rare. Thanks for looking into it!
