### ISSUE TITLE
Sound problems after exe update

### ISSUE THREAD

**Issue by aorushome** [themrdemonized/STALKER-Anomaly-modded-exes#76]
Hey man,

thanks for your hard work and consistency.

I noticed an issue after updating from 28th july 2023 executable to the latest one.
Many inventory sounds are cut short or in half, sometimes they dont play at all.

The issue appears at the following instances:

selling or buying
picking up items from ground or inventory (very noticeable when holding shift to transfer items quickly)
looting sound from "looting takes time" mod
drawing tools from "Knife, Bolt and Grenade Holster Sounds" mod
toggle helmet removal from "Toggle Helmet Hotkey" mod

Thanks for your time.

**Comment by themrdemonized** [comment]
Try this script, it will fix some sounds, but you probably have issues elsewhere
[Sound Object Bugfix Script.zip](https://github.com/themrdemonized/STALKER-Anomaly-modded-exes/files/14821046/Sound.Object.Bugfix.Script.zip)

**Comment by aorushome** [comment]
> Try this script, it will fix some sounds, but you probably have issues elsewhere [Sound Object Bugfix Script.zip](https://github.com/themrdemonized/STALKER-Anomaly-modded-exes/files/14821046/Sound.Object.Bugfix.Script.zip)

Thanks, it fixed all the errors mentioned above.
