### ISSUE TITLE
Crash when entering Dead City

### ISSUE THREAD

**Issue by billlcarr** [themrdemonized/STALKER-Anomaly-modded-exes#78]
This looks like a corrupt save issue, but I'm hoping you might know how something like this could happen. I noticed today that if I try to go to Dead City, I get a CTD before it finishes loading. I went back to earlier saves to test, and it looks like it's been this way for a month and I just didn't realize it. With a save I made a month ago at 3:10PM I can travel to Dead City no problem. But a save I made at 4:41PM that same day crashes to desktop during the loading screen when traveling there. And it happens with every save I made after that up to today. There's no crash when traveling there in a new game, so I'm starting over and hoping it was just a glitch... I've attached the MDMP file. Any help in preventing something like this in the future would be greatly appreciated.
This is at the end of the log-

!WARNING : level.object_by_id(nil) called! [6]
SWMtrue [2]
!WARNING : level.object_by_id(nil) called! [5]
stack trace:

 

SymInit: Symbol-SearchPath: '.;G:\Games\S.T.A.L.K.E.R. - Anomaly;G:\Games\S.T.A.L.K.E.R. - Anomaly\bin;C:\WINDOWS;C:\WINDOWS\system32;', symOptions: 530, UserName: 'Dreamhive'
OS-Version: 6.2.9200 () 0x300-0x1
G:\Games\S.T.A.L.K.E.R. - Anomaly\bin\AnomalyDX11AVX.exe:AnomalyDX11AVX.exe (0000000140000000), size: 16203776 (result: 0), SymType: '-exported-', PDB: 'G:\Games\S.T.A.L.K.E.R. - Anomaly\bin\AnomalyDX11AVX.exe'
at address 0x00007FFA5259543C

Here's the MDMP file-

[xray_dreamhive_05-19-24_10-49-45.zip](https://github.com/themrdemonized/STALKER-Anomaly-modded-exes/files/15370048/xray_dreamhive_05-19-24_10-49-45.zip)

Here's the full log as well-

[xray_dreamhive.log](https://github.com/themrdemonized/STALKER-Anomaly-modded-exes/files/15370991/xray_dreamhive.log)

**Comment by themrdemonized** [comment]
hi, unfortuntaly i can't see the error, Try it with the latest modded exes version

**Comment by billlcarr** [comment]
Thanks! I installed the newest executables and reproduced the crash. Here's the log and MDMP

[xray_dreamhive.log](https://github.com/themrdemonized/STALKER-Anomaly-modded-exes/files/15376008/xray_dreamhive.log)

[xray_dreamhive_05-20-24_05-34-50.zip](https://github.com/themrdemonized/STALKER-Anomaly-modded-exes/files/15376009/xray_dreamhive_05-20-24_05-34-50.zip)

**Comment by billlcarr** [comment]
I'll do that. Thanks so much for your help!
