### ISSUE TITLE
Shader compilation failed

### ISSUE THREAD

**Issue by capjay45** [themrdemonized/STALKER-Anomaly-modded-exes#79]
* Detected CPU: AMD Ryzen 7 3800X 8-Core Processor              [AuthenticAMD], F15/M1/S0, 3903.00 mhz, 38-clk 'rdtsc'
* CPU features: RDTSC, MMX, SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2, HTT
* CPU cores/threads: 8/16

Found commandline file!
Initializing File System...
using fs-ltx fsgame.ltx
File System Ready...
FS: 62811 files cached 67 archives, 12109Kb memory used.
Init FileSystem 7.970360 sec
'xrCore' build 9237, May 23 2024

Modded exes version 20240523

Game started: 20.06.2024 02:37:46.536

-----loading c:/anomaly\gamedata\configs\system.ltx [2]
X-Ray Monolith v1.5.2
gamedata: 'anims\itemuse_anm_effects\beloved_camera.anm'
gamedata: 'configs\axr_options.ltx'
gamedata: 'configs\cache_dbg.ltx'
gamedata: 'configs\creatures\actor.ltx'
gamedata: 'configs\creatures\actor_hud_hand_animations.ltx'
gamedata: 'configs\creatures\damages.ltx'
gamedata: 'configs\creatures\spawn_sections_general.ltx'
gamedata: 'configs\gameplay\character_desc_agroprom.xml'
gamedata: 'configs\gameplay\character_desc_bar.xml'
gamedata: 'configs\gameplay\character_desc_darkvalley.xml'
gamedata: 'configs\gameplay\character_desc_deadcity.xml'
gamedata: 'configs\gameplay\character_desc_escape.xml'
gamedata: 'configs\gameplay\character_desc_garbage.xml'
gamedata: 'configs\gameplay\character_desc_general.xml'
gamedata: 'configs\gameplay\character_desc_general_army.xml'
gamedata: 'configs\gameplay\character_desc_general_army_dux.xml'
gamedata: 'configs\gameplay\character_desc_general_bandit.xml'
gamedata: 'configs\gameplay\character_desc_general_bandit_dux.xml'
gamedata: 'configs\gameplay\character_desc_general_csky.xml'
gamedata: 'configs\gameplay\character_desc_general_csky_dux.xml'
gamedata: 'configs\gameplay\character_desc_general_dolg.xml'
gamedata: 'configs\gameplay\character_desc_general_dolg_dux.xml'
gamedata: 'configs\gameplay\character_desc_general_ecolog.xml'
gamedata: 'configs\gameplay\character_desc_general_ecolog_dux.xml'
gamedata: 'configs\gameplay\character_desc_general_freedom.xml'
gamedata: 'configs\gameplay\character_desc_general_freedom_dux.xml'
gamedata: 'configs\gameplay\character_desc_general_greh.xml'
gamedata: 'configs\gameplay\character_desc_general_greh_dux.xml'
gamedata: 'configs\gameplay\character_desc_general_isg.xml'
gamedata: 'configs\gameplay\character_desc_general_isg_dux.xml'
gamedata: 'configs\gameplay\character_desc_general_killer.xml'
gamedata: 'configs\gameplay\character_desc_general_killer_dux.xml'
gamedata: 'configs\gameplay\character_desc_general_monolith.xml'
gamedata: 'configs\gameplay\character_desc_general_monolith_dux.xml'
gamedata: 'configs\gameplay\character_desc_general_renegade.xml'
gamedata: 'configs\gameplay\character_desc_general_renegade_dux.xml'
gamedata: 'configs\gameplay\character_desc_general_stalker.xml'
gamedata: 'configs\gameplay\character_desc_general_stalker_dux.xml'
gamedata: 'configs\gameplay\character_desc_general_zombied.xml'
gamedata: 'configs\gameplay\character_desc_general_zombied_dux.xml'
gamedata: 'configs\gameplay\character_desc_jupiter.xml'
gamedata: 'configs\gameplay\character_desc_marsh.xml'
gamedata: 'configs\gameplay\character_desc_military.xml'
gamedata: 'configs\gameplay\character_desc_pripyat.xml'
gamedata: 'configs\gameplay\character_desc_red_forest.xml'
gamedata: 'configs\gameplay\character_desc_truck.xml'
gamedata: 'configs\gameplay\character_desc_yantar.xml'
gamedata: 'configs\gameplay\character_desc_zaton.xml'
gamedata: 'configs\gameplay\npc_profile.xml'
gamedata: 'configs\gameplay\profiles\character_desc_army_0.xml'
gamedata: 'configs\gameplay\profiles\character_desc_army_1.xml'
gamedata: 'configs\gameplay\profiles\character_desc_army_2.xml'
gamedata: 'configs\gameplay\profiles\character_desc_army_3.xml'
gamedata: 'configs\gameplay\profiles\character_desc_army_4.xml'
gamedata: 'configs\gameplay\profiles\character_desc_army_5.xml'
gamedata: 'configs\gameplay\profiles\character_desc_army_special.xml'
gamedata: 'configs\gameplay\profiles\character_desc_bandit_0.xml'
gamedata: 'configs\gameplay\profiles\character_desc_bandit_1.xml'
gamedata: 'configs\gameplay\profiles\character_desc_bandit_2.xml'
gamedata: 'configs\gameplay\profiles\character_desc_bandit_3.xml'
gamedata: 'configs\gameplay\profiles\character_desc_bandit_4.xml'
gamedata: 'configs\gameplay\profiles\character_desc_bandit_special.xml'
gamedata: 'configs\gameplay\profiles\character_desc_csky_0.xml'
gamedata: 'configs\gameplay\profiles\character_desc_csky_1.xml'
gamedata: 'configs\gameplay\profiles\character_desc_csky_2.xml'
gamedata: 'configs\gameplay\profiles\character_desc_csky_3.xml'
gamedata: 'configs\gameplay\profiles\character_desc_csky_4.xml'
gamedata: 'configs\gameplay\profiles\character_desc_csky_special.xml'
gamedata: 'configs\gameplay\profiles\character_desc_dolg_0.xml'
gamedata: 'configs\gameplay\profiles\character_desc_dolg_1.xml'
gamedata: 'configs\gameplay\profiles\character_desc_dolg_2.xml'
gamedata: 'configs\gameplay\profiles\character_desc_dolg_3.xml'
gamedata: 'configs\gameplay\profiles\character_desc_dolg_4.xml'
gamedata: 'configs\gameplay\profiles\character_desc_dolg_special.xml'
gamedata: 'configs\gameplay\profiles\character_desc_ecolog_0.xml'
gamedata: 'configs\gameplay\profiles\character_desc_ecolog_01.xml'
gamedata: 'configs\gameplay\profiles\character_desc_ecolog_1.xml'
gamedata: 'configs\gameplay\profiles\character_desc_ecolog_2.xml'
gamedata: 'configs\gameplay\profiles\character_desc_ecolog_3.xml'
gamedata: 'configs\gameplay\profiles\character_desc_ecolog_4.xml'
gamedata: 'configs\gameplay\profiles\character_desc_ecolog_5.xml'
gamedata: 'configs\gameplay\profiles\character_desc_ecolog_special.xml'
gamedata: 'configs\gameplay\profiles\character_desc_freedom_0.xml'
gamedata: 'configs\gameplay\profiles\character_desc_freedom_1.xml'
gamedata: 'configs\gameplay\profiles\character_desc_freedom_2.xml'
gamedata: 'configs\gameplay\profiles\character_desc_freedom_3.xml'
gamedata: 'configs\gameplay\profiles\character_desc_freedom_4.xml'
gamedata: 'configs\gameplay\profiles\character_desc_freedom_special.xml'
gamedata: 'configs\gameplay\profiles\character_desc_greh_0.xml'
gamedata: 'configs\gameplay\profiles\character_desc_greh_1.xml'
gamedata: 'configs\gameplay\profiles\character_desc_greh_2.xml'
gamedata: 'configs\gameplay\profiles\character_desc_greh_3.xml'
gamedata: 'configs\gameplay\profiles\character_desc_greh_4.xml'
gamedata: 'configs\gameplay\profiles\character_desc_greh_special.xml'
gamedata: 'configs\gameplay\profiles\character_desc_isg_0.xml'
gamedata: 'configs\gameplay\profiles\character_desc_isg_1.xml'
gamedata: 'configs\gameplay\profiles\character_desc_isg_2.xml'
gamedata: 'configs\gameplay\profiles\character_desc_isg_3.xml'
gamedata: 'configs\gameplay\profiles\character_desc_isg_4.xml'
gamedata: 'configs\gameplay\profiles\character_desc_isg_5.xml'
gamedata: ... 59326 more ...
Initializing Engine...
Starting INPUT device...
Loading DLL: xrRender_R4.dll
Available render modes[1]:
[renderer_r4]
command line "c:\anomaly\bin\anomalydx11avx.exe" -smap2048 -dbg 
Executing config-script "user.ltx"...
[c:/anomaly\appdata\user.ltx] successfully loaded.
Loading DLL: xrRender_R4.dll
Loading DLL: xrGame.dll
* [x-ray]: Full Memory Stats
* [win32]: free[137434340308 K], reserved[4360656 K], committed[252444 K]
* [ D3D ]: textures[0 K]
* [x-ray]: process heap[65968 K]
* [x-ray]: economy: strings[65896 K], smem[0 K]
SOUND: OpenAL: enumerate devices...
SOUND: OpenAL: EnumerationExtension Present
dir[1]=C:\Anomaly\
dir[2]=C:\Anomaly\bin\
dir[3]=C:\WINDOWS\system32\
CleanDeviceSpecifierList
CleanDeviceSpecifierList OpenAL Soft
devices OpenAL Soft
SOUND: OpenAL: system  default SndDevice name is 
SOUND: OpenAL: All available devices:
1. OpenAL Soft, Spec Version 1.1  eax[0] efx[no] xram[no]
Executing config-script "c:/anomaly\gamedata\configs\default_controls.ltx"...
[c:/anomaly\gamedata\configs\default_controls.ltx] successfully loaded.
Executing config-script "user.ltx"...
Executing config-script "c:/anomaly\gamedata\configs\rspec_default.ltx"...
[c:/anomaly\gamedata\configs\rspec_default.ltx] successfully loaded.
Executing config-script "c:/anomaly\gamedata\configs\default_controls.ltx"...
[c:/anomaly\gamedata\configs\default_controls.ltx] successfully loaded.
[c:/anomaly\appdata\user.ltx] successfully loaded.
SOUND: Selected device is OpenAL Soft
* sound: EAX 2.0 extension: absent
* sound: EAX 2.0 deferred: absent
* sound : cache: 524296 kb, 38848 lines, 13820 bpl
Starting RENDER device...
* GPU [vendor:1002]-[device:687F]: Radeon RX Vega
* CREATE: DeviceREF: 3
*     Texture memory: 8120 M
* GPU shading: vs(0/4.0/40), ps(0/4.0/40)
* GPU vertex cache: unrecognized, 24
* NVAPI is missing.
* Starting rendering as 2-GPU.
* DVB created: 4096K
* DIB created: 512K
* HWDST/PCF supported and used
* Managed textures disabled
- SSS HUD RAINDROPS SHADER INSTALLED 0
- SSS RAIN SHADER INSTALLED 0
- SSS BLOOD SHADER INSTALLED 0
- SSS BRANCHES SHADER INSTALLED 1
- SSS SSR SHADER INSTALLED 0
- SSS TERRAIN SHADER INSTALLED 0
- SSS VOLUMETRIC SHADER INSTALLED 0
THM chunk 2072 fixed, wrong size = 40, correct size = 39
THM chunk 2072 fixed, wrong size = 40, correct size = 37
DX10: c:/anomaly\gamedata\shaders\r3\heatvision.ps is missing. Replace with stub_default.ps
DX10: c:/anomaly\gamedata\shaders\r3\ssfx_ssr.ps is missing. Replace with stub_default.ps
DX10: c:/anomaly\gamedata\shaders\r3\ssfx_ssr_blur.ps is missing. Replace with stub_default.ps
DX10: c:/anomaly\gamedata\shaders\r3\ssfx_ssr_combine.ps is missing. Replace with stub_default.ps
DX10: c:/anomaly\gamedata\shaders\r3\ssfx_ssr_noblur.ps is missing. Replace with stub_default.ps
DX10: c:/anomaly\gamedata\shaders\r3\ssfx_volumetric_blur.ps is missing. Replace with stub_default.ps
DX10: Shader 'ssfx_dumb' not found in library.
!  c:/anomaly\appdata\shaders_cache\r4\combine_1_msaa_0.ps\20481111001100000000001000001101010131102001121000
! error:  common_functions.h(43,34): warning X3206: implicit truncation of vector type
common_functions.h(63,2): warning X3206: implicit truncation of vector type
common_functions.h(68,49): warning X3206: implicit truncation of vector type
common_functions.h(100,2): warning X3206: implicit truncation of vector type
gbuffer_stage.h(123,24): warning X3206: 'Load': implicit truncation of vector type
gbuffer_stage.h(124,23): warning X3206: 'Load': implicit truncation of vector type
night_vision.h(360,37): warning X3206: 'Load': implicit truncation of vector type
night_vision.h(379,30): warning X3206: 'Load': implicit truncation of vector type
hmodel.h(19,15): warning X3206: 'mul': implicit truncation of vector type
hmodel.h(28,17): warning X3206: 'mul': implicit truncation of vector type
hmodel.h(38,9): warning X3206: implicit truncation of vector type
hmodel.h(39,9): warning X3206: implicit truncation of vector type
hmodel.h(52,9): warning X3206: implicit truncation of vector type
hmodel.h(53,9): warning X3206: implicit truncation of vector type
combine_1.ps(8,10): error X1507: failed to open source file: 'ssr.h'

**Comment by capjay45** [comment]
I have cleared shader cache

**Comment by capjay45** [comment]
Nevermind, I think I just have to disabled all mods, launch, re-enable mods, sorted

**Comment by themrdemonized** [comment]
You have problems or conflicts with shader mods, ask their authors to help, not a modded exe issue

**Comment by capjay45** [comment]
Thanks for helping me clear this up, It was Modded exes and SSS
conflicting, I forgot that modded exes has SSS built in. Thanks so much
