### ISSUE TITLE
Unknown crash for modded exe

### ISSUE THREAD

**Issue by EriczjrWinter** [themrdemonized/STALKER-Anomaly-modded-exes#80]
[xray_ericz_07-06-24_13-15-26.zip](https://github.com/user-attachments/files/16114973/xray_ericz_07-06-24_13-15-26.zip)

**Comment by themrdemonized** [comment]
please post the log file as well

**Comment by EriczjrWinter** [comment]
> please post the log file as well

[xray_ericz.log](https://github.com/user-attachments/files/16115270/xray_ericz.log)

**Comment by themrdemonized** [comment]
Are you trying to use enemy-detecting scope such as gauss rifle one

**Comment by EriczjrWinter** [comment]
> Are you trying to use enemy-detecting scope such as gauss rifle one

Yes, I was using the gauss rifle to aim at a dog and then fired.
I have done this before, and no similar crash has occurred.

**Comment by themrdemonized** [comment]
yea its probably a random bug, cause in the stack trace it tries to refer to some object it tries to detect, but it was destroyed or not created in the first place, a stale null pointer. I probably can add a safe check for this in the next version, hope it helps

**Comment by EriczjrWinter** [comment]
> yea its probably a random bug, cause in the stack trace it tries to refer to some object it tries to detect, but it was destroyed or not created in the first place, a stale null pointer. I probably can add a safe check for this in the next version, hope it helps

thanks for your help.
