### ISSUE TITLE
Снижение фпс при использовании огнестрельного оружия с лазером

### ISSUE THREAD

**Issue by MotaRin** [themrdemonized/STALKER-Anomaly-modded-exes#89]
Снижение фпс при использовании огнестрельного оружия с лазером на DX8/DX9 в версии от 2024.09.04, 2024.8.25 тоже. Данная проблема отсутствует если использовать exe'шники от 2024.8.10

**Comment by themrdemonized** [comment]
данный баг из-за последнего SSS апдейта, ждем апдейта
