### ISSUE TITLE
Lua Unlocalizer Doesn't Unlocalize If The Local Declaration Is Indented Too Much

### ISSUE THREAD

**Issue by AndrewJAHogue** [themrdemonized/STALKER-Anomaly-modded-exes#90]
After attempting to unlocalize a script's local functions, I've figured out if the local declaration is indented incorrectly, it won't be unlocalized.
Example:
item_device.script
```
local function on_key_hold(key)
...
end
```
This unlocalizes correctly and returns a function value in another script
```
local function on_key_hold(key)
     ...
end
                local function on_key_release(key)
                     ...
                end
```
`on_key_release` returns an nil value when called.
Fixing the indentation fixes the issue.

**Comment by themrdemonized** [comment]
Yes, unlocalizer is designed that way, to distinguish top level local variables vs locals inside a scope. If you have top level locals intended for some reason, that's a script issue
