### ISSUE TITLE
Why am I dropping frames when shooting with latest Modded Exe's??

### ISSUE THREAD

**Issue by Masked-Man24** [themrdemonized/STALKER-Anomaly-modded-exes#92]
In the debug menu I noticed that I drop in frames when firing any weapon. This did not happen with older exe's.

**Comment by themrdemonized** [comment]
by the latest you mean 2024.09.14 version?

**Comment by Masked-Man24** [comment]
> by the latest you mean 2024.09.14 version? Anyways we'll check it out

Yea, so I normally play on Borderless Windowed, and when I fired any weapon my fps would tank dramatically. When I switched to fullscreen my fps boosted back up, but there were still some performance drops when firing a weapon in ads or hipfire.

**Comment by themrdemonized** [comment]
Relax, issues might happen and we'll try to fix them

**Comment by themrdemonized** [comment]
Try the latest 2024.09.15 version, see if its better

**Comment by Masked-Man24** [comment]
Much better, now. Tested in fullscreen and borderless windowed, frames much more stable.
